const BASE = '/api';
let unauthorizedHandler = null;
export function setUnauthorizedHandler(handler) { unauthorizedHandler = handler; }
export class ApiError extends Error { constructor(message, { code = '', status = 0 } = {}) { super(message); this.name = 'ApiError'; this.code = code; this.status = status; this.fallbackMessage = message; } }
async function request(path, options = {}) {
  const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
  const response = await fetch(`${BASE}${path}`, { credentials: 'same-origin', ...options, headers });
  let data = null; try { data = await response.json(); } catch { /* empty */ }
  if (!response.ok) { const error = new ApiError(data?.error || `Request failed (${response.status})`, { code: data?.code || '', status: response.status }); if (response.status === 401) unauthorizedHandler?.(error); throw error; }
  return data;
}
export const api = {
  me: () => request('/auth/me'), login: (username, password) => request('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }), register: (body) => request('/auth/register', { method: 'POST', body: JSON.stringify(body) }), logout: () => request('/auth/logout', { method: 'POST' }), changePassword: (currentPassword, newPassword) => request('/auth/change-password', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) }), getProfile:()=>request('/auth/profile'), updateProfile:(body)=>request('/auth/profile',{method:'PATCH',body:JSON.stringify(body)}),
  listCategories: (scope = 'public') => request(`/categories?scope=${scope}`), createCategory: (body) => request('/categories', { method: 'POST', body: JSON.stringify(body) }), updateCategory: (id, body) => request(`/categories/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), getCategoryImpact: (id) => request(`/categories/${id}/impact`), deleteCategory: (id, body = {}) => request(`/categories/${id}`, { method: 'DELETE', body: JSON.stringify(body) }), reorderCategories: (scope, parentId, orderedIds) => request('/categories/reorder', { method: 'POST', body: JSON.stringify({ scope, parentId, orderedIds }) }),
  listItems: (scope = 'public') => request(`/items?scope=${scope}`), inspectItemUrl: (scope, url) => request('/items/metadata', { method: 'POST', body: JSON.stringify({ scope, url }) }), bulkInspectItems: (scope, ids) => request('/items/bulk-metadata', { method: 'POST', body: JSON.stringify({ scope, ids }) }), searchItems: (q) => request(`/search?q=${encodeURIComponent(q)}`), createItem: (body) => request('/items', { method: 'POST', body: JSON.stringify(body) }), updateItem: (id, body) => request(`/items/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), bulkUpdateItems: (scope, ids, patch) => request('/items/bulk-update', { method: 'POST', body: JSON.stringify({ scope, ids, patch }) }), bulkDeleteItems: (scope, ids) => request('/items/bulk-delete', { method: 'POST', body: JSON.stringify({ scope, ids }) }), deleteItem: (id) => request(`/items/${id}`, { method: 'DELETE' }), clickItem: (id, context = {}) => request(`/items/${id}/click`, { method: 'POST', body: JSON.stringify(context) }), checkItem: (id) => request(`/items/${id}/check`, { method: 'POST' }), checkAll: (scope) => request('/items/check-all', { method: 'POST', body: JSON.stringify({ scope }) }),
  discussAi: (scope,text,locale,conversationId=null) => request(`/ai/${scope}/discussions`,{method:'POST',body:JSON.stringify({text,locale,conversationId})}), createAiPlan: (scope, text, locale,conversationId=null) => request(`/ai/${scope}/plans`, { method: 'POST', body: JSON.stringify({ text, locale,conversationId }) }), getAiPlan: (id) => request(`/ai/plans/${id}`), executeAiPlan: (id, body) => request(`/ai/plans/${id}/execute`, { method: 'POST', body: JSON.stringify(body) }), undoAiPlan: (id, idempotencyKey) => request(`/ai/plans/${id}/undo`, { method: 'POST', body: JSON.stringify({ idempotencyKey }) }), aiStatus: () => request('/ai/status'),
  createAiConversation:(scope,title='')=>request('/ai/conversations',{method:'POST',body:JSON.stringify({scope,title})}),listAiConversations:()=>request('/ai/conversations'),getAiConversation:(id)=>request(`/ai/conversations/${id}`),
  startAiOrganize:(scope,selection=null)=>request(`/ai/${scope}/organize`,{method:'POST',body:JSON.stringify({selection})}),startEmbeddingIndex:(scope)=>request(`/ai/${scope}/index`,{method:'POST',body:'{}'}),startAiReport:(scope)=>request(`/ai/${scope}/reports`,{method:'POST',body:'{}'}),startContentAnalysis:(scope)=>request(`/ai/${scope}/content-analysis`,{method:'POST',body:'{}'}),getAiJob:(id)=>request(`/ai/jobs/${id}`),listAiJobs:()=>request('/ai/jobs'),listAiReports:()=>request('/ai/reports'),listNotifications:()=>request('/ai/notifications'),readNotification:(id)=>request(`/ai/notifications/${id}/read`,{method:'POST',body:'{}'}),
  getPublicSettings: () => request('/settings/public'), getAdminSettings: () => request('/settings/admin'), updateAdminSettings: (body) => request('/settings/admin', { method: 'PUT', body: JSON.stringify(body) }),
  addAiModel: (body) => request('/settings/admin/ai-models', { method:'POST', body:JSON.stringify(body) }), updateAiModel: (id,body) => request(`/settings/admin/ai-models/${id}`, { method:'PATCH', body:JSON.stringify(body) }), deleteAiModel: (id) => request(`/settings/admin/ai-models/${id}`, { method:'DELETE' }), setDefaultAiModel: (id) => request(`/settings/admin/ai-models/${id}/default`, { method:'POST', body:'{}' }), testAiModel: (body) => request('/settings/admin/ai-models/test', { method:'POST', body:JSON.stringify(body) }),
  updateEmbedding:(body)=>request('/settings/admin/embedding',{method:'PUT',body:JSON.stringify(body)}),testEmbedding:(body={})=>request('/settings/admin/embedding/test',{method:'POST',body:JSON.stringify(body)}),
  listContentDomains:()=>request('/settings/admin/content-domains'),updateContentDomain:(hostname,allowContent)=>request('/settings/admin/content-domain',{method:'PUT',body:JSON.stringify({hostname,allowContent})}),
  getAiUsage:(days=30)=>request(`/settings/admin/ai-usage?days=${days}`),
  listUsers: () => request('/admin/users'), getUser: (id) => request(`/admin/users/${id}`), createUser: (body) => request('/admin/users', { method: 'POST', body: JSON.stringify(body) }), updateUser: (id, body) => request(`/admin/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), deleteUser: (id) => request(`/admin/users/${id}`, { method:'DELETE' }), resetUserPassword: (id, body = {}) => request(`/admin/users/${id}/reset-password`, { method: 'POST', body: JSON.stringify(body) }), listLegacySpaces: () => request('/admin/legacy-spaces'), assignLegacySpace: (id, userId) => request(`/admin/legacy-spaces/${id}/assign`, { method: 'POST', body: JSON.stringify({ userId }) }), getAnalytics: (days = 30) => request(`/admin/analytics/summary?days=${days}`), getAuditEvents: (page = 1, pageSize = 20) => request(`/admin/analytics/audit?page=${page}&pageSize=${pageSize}`),
  listShares:()=>request('/shares'),getShare:(id)=>request(`/shares/${id}`),createShare:(body)=>request('/shares',{method:'POST',body:JSON.stringify(body)}),respondShare:(id,body)=>request(`/shares/${id}/respond`,{method:'POST',body:JSON.stringify(body)}),exportResources:(scope,selection)=>request('/transfer/export',{method:'POST',body:JSON.stringify({scope,selection})}),previewImport:(scope,payload,format='auto')=>request('/transfer/preview',{method:'POST',body:JSON.stringify({scope,payload,format})}),importResources:(scope,body)=>request('/transfer/import',{method:'POST',body:JSON.stringify({scope,...body})}),
};
