const BASE = '/api';
let unauthorizedHandler = null;
export function setUnauthorizedHandler(handler) { unauthorizedHandler = handler; }
export class ApiError extends Error { constructor(message, { code = '', status = 0 } = {}) { super(message); this.name = 'ApiError'; this.code = code; this.status = status; this.fallbackMessage = message; } }
async function request(path, options = {}) {
  const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
  const response = await fetch(`${BASE}${path}`, { credentials: 'same-origin', ...options, headers });
  let data = null; try { data = await response.json(); } catch { /* empty */ }
  if (!response.ok) { const error = new ApiError(data?.error || `Request failed (${response.status})`, { code: data?.code || '', status: response.status }); if (response.status === 401) unauthorizedHandler?.(error); throw error; }
  return data;
}
async function streamRequest(path,body,{onMeta,onDelta,onStage,onUsage,onTools,onResult,onDone,onEvent,signal}={}){
  const response=await fetch(`${BASE}${path}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify(body),signal});
  if(!response.ok){let data=null;try{data=await response.json();}catch{/* empty */}const error=new ApiError(data?.error||`Request failed (${response.status})`,{code:data?.code||'',status:response.status});if(response.status===401)unauthorizedHandler?.(error);throw error;}
  if(!response.body)throw new ApiError('浏览器不支持流式响应',{code:'AI_STREAM_UNAVAILABLE',status:500});
  const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=null,result=null,receivedDelta=false;
  const consume=line=>{
    if(!line.trim())return;
    let event;try{event=JSON.parse(line);}catch{return;}
    onEvent?.(event);
    if(event.type==='meta')onMeta?.(event);
    else if(event.type==='delta'){receivedDelta=receivedDelta||Boolean(event.content);onDelta?.(event.content||'');}
    else if(event.type==='stage')onStage?.(event);
    else if(event.type==='usage')onUsage?.(event);
    else if(event.type==='tools')onTools?.(event);
    else if(event.type==='result'){result=event.result;onResult?.(event.result);}
    else if(event.type==='done'){completed=event;onDone?.(event);}
    else if(event.type==='error'){const error=new ApiError(event.message||'AI 流式请求失败',{code:event.code||'AI_DISCUSSION_FAILED',status:event.status||502});Object.assign(error,{partial:Boolean(event.partial),retryable:Boolean(event.retryable),run:event.run||null});throw error;}
  };
  try{
    while(true){
      const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});
      const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';
      for(const line of lines)consume(line);
      if(done)break;
    }
  }catch(cause){if(cause instanceof ApiError)throw cause;const error=new ApiError(receivedDelta?'AI 流式响应意外中断':'AI 流式请求失败',{code:receivedDelta?'AI_STREAM_INTERRUPTED':'AI_UPSTREAM_REQUEST_FAILED',status:502});Object.assign(error,{partial:receivedDelta,retryable:receivedDelta,cause});throw error;}
  if(buffer.trim())consume(buffer);
  if(!completed){const error=new ApiError('AI 流式响应意外中断',{code:'AI_STREAM_INTERRUPTED',status:502});Object.assign(error,{partial:receivedDelta,retryable:receivedDelta});throw error;}
  return {...completed,result};
}
export const api = {
  me: () => request('/auth/me'), login: (username, password) => request('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }), register: (body) => request('/auth/register', { method: 'POST', body: JSON.stringify(body) }), logout: () => request('/auth/logout', { method: 'POST' }), changePassword: (currentPassword, newPassword) => request('/auth/change-password', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) }), getProfile:()=>request('/auth/profile'), updateProfile:(body)=>request('/auth/profile',{method:'PATCH',body:JSON.stringify(body)}),uploadAvatar:(dataUrl)=>request('/auth/avatar',{method:'POST',body:JSON.stringify({dataUrl})}),
  listCategories: (scope = 'public') => request(`/categories?scope=${scope}`), createCategory: (body) => request('/categories', { method: 'POST', body: JSON.stringify(body) }), updateCategory: (id, body) => request(`/categories/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), moveCategory: (id, body) => request(`/categories/${id}/move`, { method:'POST',body:JSON.stringify(body) }), getCategoryImpact: (id) => request(`/categories/${id}/impact`), deleteCategory: (id, body = {}) => request(`/categories/${id}`, { method: 'DELETE', body: JSON.stringify(body) }), reorderCategories: (scope, parentId, orderedIds) => request('/categories/reorder', { method: 'POST', body: JSON.stringify({ scope, parentId, orderedIds }) }),
  getCategoryAccess:(id)=>request(`/categories/${id}/access-default`),updateCategoryAccess:(id,body)=>request(`/categories/${id}/access-default`,{method:'PUT',body:JSON.stringify(body)}),previewCategoryAccess:(id,body)=>request(`/categories/${id}/access-default/preview`,{method:'POST',body:JSON.stringify(body)}),applyCategoryAccess:(id,body)=>request(`/categories/${id}/access-default/apply`,{method:'POST',body:JSON.stringify(body)}),
  getWorkspace: (scope = 'public', version = '') => { const params = new URLSearchParams({ scope }); if (version) params.set('version', version); return request(`/workspace?${params}`); },
  listItems: (scope = 'public') => request(`/items?scope=${scope}`), setItemFavorite: (id, favorite) => request(`/items/${id}/favorite`, { method:'PUT', body:JSON.stringify({ favorite }) }), inspectItemUrl: (scope, url) => request('/items/metadata', { method: 'POST', body: JSON.stringify({ scope, url }) }), bulkInspectItems: (scope, ids) => request('/items/bulk-metadata', { method: 'POST', body: JSON.stringify({ scope, ids }) }), searchItems: (q) => request(`/search?q=${encodeURIComponent(q)}`), createItem: (body) => request('/items', { method: 'POST', body: JSON.stringify(body) }), updateItem: (id, body) => request(`/items/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), bulkUpdateItems: (scope, ids, patch) => request('/items/bulk-update', { method: 'POST', body: JSON.stringify({ scope, ids, patch }) }), bulkDeleteItems: (scope, ids) => request('/items/bulk-delete', { method: 'POST', body: JSON.stringify({ scope, ids }) }), deleteItem: (id) => request(`/items/${id}`, { method: 'DELETE' }), clickItem: (id, context = {}) => request(`/items/${id}/click`, { method: 'POST', body: JSON.stringify(context) }), checkItem: (id) => request(`/items/${id}/check`, { method: 'POST' }), checkAll: (scope) => request('/items/check-all', { method: 'POST', body: JSON.stringify({ scope }) }), getAvailabilitySummaries:(ids,days=30)=>request('/items/availability-summaries',{method:'POST',body:JSON.stringify({ids,days})}),getItemAvailability:(id,days=30)=>request(`/items/${id}/availability?days=${days}`),getItemAvailabilityDay:(id,date)=>request(`/items/${id}/availability-day?date=${encodeURIComponent(date)}`),
  getItemAccess:(id)=>request(`/items/${id}/access`),updateItemAccess:(id,body)=>request(`/items/${id}/access`,{method:'PUT',body:JSON.stringify(body)}),bulkUpdateAccess:(scope,ids,access)=>request('/items/bulk-access',{method:'POST',body:JSON.stringify({scope,ids,access})}),
  discussAi: (scope,text,locale,conversationId=null) => request(`/ai/${scope}/discussions`,{method:'POST',body:JSON.stringify({text,locale,conversationId})}), discussAiStream:(scope,text,locale,conversationId=null,handlers={})=>streamRequest(`/ai/${scope}/discussions/stream`,{text,locale,conversationId},handlers), runAiInstruction:(scope,text,locale,conversationId=null)=>request(`/ai/${scope}/instructions`,{method:'POST',body:JSON.stringify({text,locale,conversationId})}), runAiInstructionStream:(scope,text,locale,conversationId=null,handlers={})=>streamRequest(`/ai/${scope}/instructions/stream`,{text,locale,conversationId},handlers), runAiQuickInstructionStream:(scope,text,locale,conversationId=null,handlers={})=>streamRequest(`/ai/${scope}/quick-instructions/stream`,{text,locale,conversationId},handlers), getAiRun:(id)=>request(`/ai/runs/${id}`), getAiReport:(id)=>request(`/ai/reports/${id}`), createAiPlan: (scope, text, locale,conversationId=null) => request(`/ai/${scope}/plans`, { method: 'POST', body: JSON.stringify({ text, locale,conversationId }) }), getAiPlan: (id) => request(`/ai/plans/${id}`), executeAiPlan: (id, body) => request(`/ai/plans/${id}/execute`, { method: 'POST', body: JSON.stringify(body) }), undoAiPlan: (id, idempotencyKey) => request(`/ai/plans/${id}/undo`, { method: 'POST', body: JSON.stringify({ idempotencyKey }) }), aiStatus: () => request('/ai/status'),
  createAiConversation:(scope,title='')=>request('/ai/conversations',{method:'POST',body:JSON.stringify({scope,title})}),listAiConversations:()=>request('/ai/conversations'),getAiConversation:(id)=>request(`/ai/conversations/${id}`),
  getPublicSettings: () => request('/settings/public'), getAdminSettings: () => request('/settings/admin'), updateAdminSettings: (body) => request('/settings/admin', { method: 'PUT', body: JSON.stringify(body) }), uploadBrandingAsset:(kind,dataUrl)=>request('/settings/admin/branding-assets',{method:'POST',body:JSON.stringify({kind,dataUrl})}),clearBrandingAsset:(kind)=>request(`/settings/admin/branding-assets/${kind}`,{method:'DELETE'}),
  getPublicInsights:(days=30)=>request(`/insights/public?days=${days}`),
  addAiModel: (body) => request('/settings/admin/ai-models', { method:'POST', body:JSON.stringify(body) }), updateAiModel: (id,body) => request(`/settings/admin/ai-models/${id}`, { method:'PATCH', body:JSON.stringify(body) }), deleteAiModel: (id) => request(`/settings/admin/ai-models/${id}`, { method:'DELETE' }), setDefaultAiModel: (id) => request(`/settings/admin/ai-models/${id}/default`, { method:'POST', body:'{}' }), testAiModel: (body) => request('/settings/admin/ai-models/test', { method:'POST', body:JSON.stringify(body) }),
  updateEmbedding:(body)=>request('/settings/admin/embedding',{method:'PUT',body:JSON.stringify(body)}),testEmbedding:(body={})=>request('/settings/admin/embedding/test',{method:'POST',body:JSON.stringify(body)}),
  getAiUsage:(days=30)=>request(`/settings/admin/ai-usage?days=${days}`),
  listUsers: () => request('/admin/users'), getUser: (id) => request(`/admin/users/${id}`), createUser: (body) => request('/admin/users', { method: 'POST', body: JSON.stringify(body) }), updateUser: (id, body) => request(`/admin/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), deleteUser: (id) => request(`/admin/users/${id}`, { method:'DELETE' }), resetUserPassword: (id, body = {}) => request(`/admin/users/${id}/reset-password`, { method: 'POST', body: JSON.stringify(body) }), listLegacySpaces: () => request('/admin/legacy-spaces'), assignLegacySpace: (id, userId) => request(`/admin/legacy-spaces/${id}/assign`, { method: 'POST', body: JSON.stringify({ userId }) }), getAnalytics: ({ days = 30, scope = 'all', ownerId = '' } = {}) => { const params = new URLSearchParams({ days:String(days),scope }); if(ownerId)params.set('ownerId',ownerId); return request(`/admin/analytics/summary?${params}`); }, getAnalyticsUsers: () => request('/admin/analytics/users'), getAuditEvents: (page = 1, pageSize = 20) => request(`/admin/analytics/audit?page=${page}&pageSize=${pageSize}`),
  listAccessGroups:()=>request('/admin/access-groups'),getAccessGroup:(id)=>request(`/admin/access-groups/${id}`),createAccessGroup:(body)=>request('/admin/access-groups',{method:'POST',body:JSON.stringify(body)}),updateAccessGroup:(id,body)=>request(`/admin/access-groups/${id}`,{method:'PATCH',body:JSON.stringify(body)}),updateAccessGroupMembers:(id,body)=>request(`/admin/access-groups/${id}/members`,{method:'PUT',body:JSON.stringify(body)}),deleteAccessGroup:(id,confirm=false)=>request(`/admin/access-groups/${id}`,{method:'DELETE',body:JSON.stringify({confirm})}),searchAccessPrincipals:(q='')=>request(`/admin/access-principals?q=${encodeURIComponent(q)}`),getAdminAvailability:({days=30,scope='all'}={})=>request(`/admin/availability?days=${days}&scope=${scope}`),checkAdminAvailabilityItem:(id)=>request(`/admin/availability/${id}/check`,{method:'POST',body:'{}'}),checkAdminAvailabilityAll:(scope='all')=>request('/admin/availability/check-all',{method:'POST',body:JSON.stringify({scope})}),
  listShares:()=>request('/shares'),getShare:(id)=>request(`/shares/${id}`),createShare:(body)=>request('/shares',{method:'POST',body:JSON.stringify(body)}),respondShare:(id,body)=>request(`/shares/${id}/respond`,{method:'POST',body:JSON.stringify(body)}),exportResources:(scope,selection)=>request('/transfer/export',{method:'POST',body:JSON.stringify({scope,selection})}),previewImport:(scope,payload,format='auto')=>request('/transfer/preview',{method:'POST',body:JSON.stringify({scope,payload,format})}),importResources:(scope,body)=>request('/transfer/import',{method:'POST',body:JSON.stringify({scope,...body})}),
};
