const express=require('express');
const crypto=require('crypto');
const {requestCommands}=require('../services/ai/openAiCompatibleProvider');
const {createPlan,serializePlan,loadPlan}=require('../services/ai/planService');
const {executePlan,undoPlan}=require('../services/ai/commandExecutor');
const {getSetting}=require('../services/settingsService');
const {requireAdmin,requireUser,requirePasswordChanged}=require('../middleware/auth');
const {realm,createNavigationService}=require('../services/navigationService');
const {audit}=require('../services/eventService');
const {jobs,intelligence}=require('../services/ai/runtime');
const {createConversationService}=require('../services/ai/conversationService');
const db=require('../db'),navigation=createNavigationService(db),conversations=createConversationService(db);
const router=express.Router();
function personalEnabled(){return getSetting('ai_personal_enabled','false')==='true';}
function sendError(res,error,fallback='AI_UPSTREAM_REQUEST_FAILED'){return res.status(error.status||502).json({code:error.code||fallback,error:error.message||'AI 操作失败'});}
function plannerContext(current,text){const q=String(text||'').toLocaleLowerCase(),categories=navigation.listCategories(current),items=navigation.listItems(current).map(item=>{const category=categories.find(row=>row.id===item.category_id);let relevance=0;for(const token of q.split(/\s+/).filter(x=>x.length>1))if(`${item.name} ${item.url} ${item.description} ${(item.tags||[]).join(' ')} ${category?.path_label||''}`.toLocaleLowerCase().includes(token))relevance+=1;return{item,relevance,category};}).sort((a,b)=>b.relevance-a.relevance||b.item.click_count-a.item.click_count).slice(0,250);return{categories:categories.map(row=>({name:row.name,path:row.path_label})),resources:items.map(({item,category})=>({name:item.name,url:item.url,description:item.description,tags:item.tags||[],category:category?.path_label||null,status:item.status}))};}
async function plan(req,res,scope){const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({code:'AI_TEXT_REQUIRED',error:'请输入描述内容'});try{const current=realm(scope,scope==='personal'?req.auth.user.id:null),locale=req.body.locale==='en'?'en':'zh-CN',conversationId=req.body.conversationId||null;let history=[];if(conversationId){const conversation=conversations.get(conversationId,req.auth.user);if(!conversation||conversation.realm_scope!==scope)throw Object.assign(new Error('对话不存在或空间不匹配'),{code:'AI_CONVERSATION_NOT_FOUND',status:404});history=conversations.messages(conversationId,req.auth.user)||[];conversations.append(conversationId,req.auth.user,{role:'user',content:text});}const result=await requestCommands(text,{locale,context:plannerContext(current,text),history,actorId:req.auth.user.id}),value=createPlan({actor:req.auth.user,current,locale,text,commands:result.commands,model:result.model,summary:result.summary,suggestions:result.suggestions});if(conversationId)conversations.append(conversationId,req.auth.user,{role:'assistant',content:result.summary||`${value.operations.length} 项操作计划`,planId:value.id,metadata:{suggestions:result.suggestions,operationCount:value.operations.length}});audit(req,'ai.plan.created',{targetType:'ai_plan',targetId:value.id,metadata:{scope,conversationId,operationTypes:value.operations.map(x=>x.op),operationCount:value.operations.length,inputHash:crypto.createHash('sha256').update(text).digest('hex')}});return res.status(201).json({...value,conversationId});}catch(error){audit(req,'ai.plan.failed',{outcome:'failure',targetType:'ai_plan',metadata:{scope,reason:error.code||'AI_PLAN_FAILED'}});return sendError(res,error,'AI_PLAN_FAILED');}}
router.post('/public/plans',requireAdmin,requirePasswordChanged,(req,res)=>plan(req,res,'public'));
router.post('/personal/plans',requireUser,requirePasswordChanged,(req,res)=>{if(!personalEnabled())return res.status(403).json({code:'AI_PERSONAL_DISABLED',error:'管理员尚未开启个人空间的 AI 资源操作'});return plan(req,res,'personal');});
router.get('/plans/:id',requireUser,requirePasswordChanged,(req,res)=>{try{return res.json(serializePlan(loadPlan(req.params.id,req.auth.user)));}catch(error){return sendError(res,error,'AI_PLAN_NOT_FOUND');}});
router.post('/plans/:id/execute',requireUser,requirePasswordChanged,(req,res)=>{try{return res.json(executePlan({id:req.params.id,actor:req.auth.user,req,idempotencyKey:req.body.idempotencyKey,confirmed:req.body.confirmed===true,confirmDestructive:Boolean(req.body.confirmDestructive)}));}catch(error){audit(req,'ai.plan.execution_failed',{outcome:'failure',targetType:'ai_plan',targetId:req.params.id,metadata:{reason:error.code||'AI_EXECUTION_FAILED'}});return sendError(res,error,'AI_EXECUTION_FAILED');}});
router.post('/plans/:id/undo',requireUser,requirePasswordChanged,(req,res)=>{try{return res.json(undoPlan({id:req.params.id,actor:req.auth.user,req,idempotencyKey:req.body.idempotencyKey}));}catch(error){audit(req,'ai.plan.undo_failed',{outcome:'failure',targetType:'ai_plan',targetId:req.params.id,metadata:{reason:error.code||'AI_UNDO_FAILED'}});return sendError(res,error,'AI_UNDO_FAILED');}});
router.get('/status',(req,res)=>{const {getEffectiveAiConfig}=require('../services/settingsService');res.json({configured:Boolean(getEffectiveAiConfig().apiKey),personalEnabled:personalEnabled()});});
router.get('/conversations',requireUser,requirePasswordChanged,(req,res)=>res.json(conversations.list(req.auth.user)));
router.post('/conversations',requireUser,requirePasswordChanged,(req,res)=>{try{const scope=req.body.scope==='public'?'public':'personal';if(scope==='public'&&req.auth.user.role!=='admin')return res.status(403).json({code:'FORBIDDEN',error:'没有公共空间操作权限'});return res.status(201).json(conversations.create(req.auth.user,realm(scope,scope==='personal'?req.auth.user.id:null),req.body.title));}catch(error){return sendError(res,error,'AI_CONVERSATION_FAILED');}});
router.get('/conversations/:id',requireUser,requirePasswordChanged,(req,res)=>{const conversation=conversations.get(req.params.id,req.auth.user),messages=conversations.messages(req.params.id,req.auth.user);return conversation&&messages?res.json({...conversations.serialize(conversation),messages}):res.status(404).json({code:'AI_CONVERSATION_NOT_FOUND',error:'对话不存在'});});
function authorizeRealm(req,res,next){const scope=req.params.scope;if(scope==='public')return requireAdmin(req,res,()=>requirePasswordChanged(req,res,next));if(scope==='personal')return requireUser(req,res,()=>requirePasswordChanged(req,res,next));return res.status(400).json({code:'INVALID_SCOPE',error:'无效空间范围'});}
function requestRealm(req){return realm(req.params.scope,req.params.scope==='personal'?req.auth.user.id:null);}
router.post('/:scope/organize',authorizeRealm,(req,res)=>{try{const job=jobs.enqueue({actor:req.auth.user,kind:'organize',realm:requestRealm(req),input:{selection:req.body.selection||null}});audit(req,'ai.organize.started',{targetType:'ai_job',targetId:job.id,metadata:{scope:req.params.scope}});return res.status(202).json(job);}catch(error){return sendError(res,error,'AI_JOB_FAILED');}});
router.post('/:scope/index',authorizeRealm,(req,res)=>{if(req.params.scope==='personal'&&!personalEnabled())return res.status(403).json({code:'AI_PERSONAL_DISABLED',error:'管理员尚未开启个人空间的 AI 能力'});try{const job=jobs.enqueue({actor:req.auth.user,kind:'embedding_index',realm:requestRealm(req)});audit(req,'ai.embedding_index.started',{targetType:'ai_job',targetId:job.id,metadata:{scope:req.params.scope}});return res.status(202).json(job);}catch(error){return sendError(res,error,'AI_JOB_FAILED');}});
router.post('/:scope/reports',authorizeRealm,(req,res)=>{try{const job=jobs.enqueue({actor:req.auth.user,kind:'report',realm:requestRealm(req)});audit(req,'ai.report.started',{targetType:'ai_job',targetId:job.id,metadata:{scope:req.params.scope}});return res.status(202).json(job);}catch(error){return sendError(res,error,'AI_JOB_FAILED');}});
router.post('/:scope/content-analysis',authorizeRealm,(req,res)=>{if(req.params.scope==='personal'&&!personalEnabled())return res.status(403).json({code:'AI_PERSONAL_DISABLED',error:'管理员尚未开启个人空间的 AI 能力'});try{const job=jobs.enqueue({actor:req.auth.user,kind:'organize',realm:requestRealm(req),input:{mode:'content'}});audit(req,'ai.content_analysis.started',{targetType:'ai_job',targetId:job.id,metadata:{scope:req.params.scope}});return res.status(202).json(job);}catch(error){return sendError(res,error,'AI_JOB_FAILED');}});
router.get('/jobs',requireUser,requirePasswordChanged,(req,res)=>res.json(jobs.list(req.auth.user,req.query.limit)));
router.get('/jobs/:id',requireUser,requirePasswordChanged,(req,res)=>{const job=jobs.get(req.params.id,req.auth.user);return job?res.json(job):res.status(404).json({code:'AI_JOB_NOT_FOUND',error:'后台任务不存在'});});
router.get('/jobs/:id/events',requireUser,requirePasswordChanged,(req,res)=>{if(!jobs.get(req.params.id,req.auth.user))return res.status(404).json({code:'AI_JOB_NOT_FOUND',error:'后台任务不存在'});res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive'});res.flushHeaders?.();let last='';const send=()=>{const job=jobs.get(req.params.id,req.auth.user);if(!job)return;const value=JSON.stringify(job);if(value!==last){res.write(`event: progress\ndata: ${value}\n\n`);last=value;}if(['succeeded','failed'].includes(job.status)){clearInterval(timer);res.end();}};const timer=setInterval(send,500);send();req.on('close',()=>clearInterval(timer));});
router.get('/reports',requireUser,requirePasswordChanged,(req,res)=>{const rows=require('../db').prepare('SELECT id,realm_scope AS scope,summary,findings_json AS findings,created_at_ms AS createdAt FROM ai_reports WHERE recipient_user_id=? ORDER BY created_at_ms DESC LIMIT 30').all(req.auth.user.id).map(row=>({...row,findings:JSON.parse(row.findings||'[]')}));res.json(rows);});
router.get('/notifications',requireUser,requirePasswordChanged,(req,res)=>{const rows=require('../db').prepare('SELECT id,kind,title,body,payload_json AS payload,read_at_ms AS readAt,created_at_ms AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at_ms DESC LIMIT 50').all(req.auth.user.id).map(row=>({...row,payload:JSON.parse(row.payload||'{}')}));res.json(rows);});
router.post('/notifications/:id/read',requireUser,requirePasswordChanged,(req,res)=>{const result=require('../db').prepare('UPDATE notifications SET read_at_ms=COALESCE(read_at_ms,?) WHERE id=? AND user_id=?').run(Date.now(),req.params.id,req.auth.user.id);return result.changes?res.json({ok:true}):res.status(404).json({code:'NOTIFICATION_NOT_FOUND',error:'通知不存在'});});
module.exports=router;
