const express = require('express');
const db = require('../db');
const { requireAdmin, requirePasswordChanged } = require('../middleware/auth');
const router = express.Router(); router.use(requireAdmin,requirePasswordChanged);
function range(req){const days=Math.min(90,Math.max(1,Number(req.query.days)||30));const to=Date.now();return{days,to,from:to-days*86400000};}
router.get('/summary',(req,res)=>{const {days,from,to}=range(req);const trend=db.prepare(`WITH RECURSIVE dates(day) AS (SELECT date(?/1000,'unixepoch') UNION ALL SELECT date(day,'+1 day') FROM dates WHERE day<date(?/1000,'unixepoch')) SELECT day,COALESCE((SELECT COUNT(*) FROM analytics_events e WHERE e.event_name='item.clicked' AND date(e.occurred_at_ms/1000,'unixepoch')=day),0) opens,COALESCE((SELECT COUNT(DISTINCT user_id) FROM analytics_events e WHERE e.event_name='item.clicked' AND e.user_id IS NOT NULL AND date(e.occurred_at_ms/1000,'unixepoch')=day),0) activeUsers FROM dates`).all(from,to);
const top=db.prepare(`SELECT COALESCE(items.name,'Deleted item') name,COUNT(*) value FROM analytics_events LEFT JOIN items ON items.id=analytics_events.item_id WHERE event_name='item.clicked' AND occurred_at_ms>=? GROUP BY analytics_events.item_id ORDER BY value DESC LIMIT 10`).all(from);
const sources=db.prepare(`SELECT COALESCE(surface,'other') name,COUNT(*) value FROM analytics_events WHERE event_name='item.clicked' AND occurred_at_ms>=? GROUP BY surface ORDER BY value DESC`).all(from);const devices=db.prepare(`SELECT COALESCE(device_class,'other') name,COUNT(*) value FROM analytics_events WHERE event_name='item.clicked' AND occurred_at_ms>=? GROUP BY device_class ORDER BY value DESC`).all(from);const spaces=db.prepare(`SELECT COALESCE(scope,'public') name,COUNT(*) value FROM analytics_events WHERE event_name='item.clicked' AND occurred_at_ms>=? GROUP BY scope`).all(from);const total=db.prepare("SELECT COUNT(*) count FROM analytics_events WHERE event_name='item.clicked' AND occurred_at_ms>=?").get(from).count;const users=db.prepare('SELECT COUNT(*) count FROM users WHERE status=\'active\'').get().count;const resources=db.prepare('SELECT COUNT(*) count FROM items').get().count;res.json({days,summary:{opens:total,activeUsers:Math.max(...trend.map(d=>d.activeUsers),0),users,resources},trend,topResources:top,sources,devices,spaces});});
router.get('/audit',(req,res)=>{const pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||20));const total=db.prepare('SELECT COUNT(*) count FROM security_audit_events').get().count;const totalPages=Math.max(1,Math.ceil(total/pageSize));const page=Math.min(totalPages,Math.max(1,Number(req.query.page)||1));const rows=db.prepare(`SELECT id,occurred_at_ms AS occurredAt,event_type AS eventType,outcome,actor_user_id AS actorUserId,actor_username AS actorUsername,actor_role AS actorRole,target_type AS targetType,target_id AS targetId,ip_prefix AS ipPrefix,browser_family AS browserFamily,os_family AS osFamily,device_class AS deviceClass,metadata_json AS metadata FROM security_audit_events ORDER BY occurred_at_ms DESC,id DESC LIMIT ? OFFSET ?`).all(pageSize,(page-1)*pageSize).map((row)=>{let metadata={};try{metadata=JSON.parse(row.metadata||'{}');}catch{}return{...row,metadata};});res.json({items:rows,pagination:{page,pageSize,total,totalPages}});});
module.exports=router;
