const crypto=require('crypto');
const defaultDb=require('../../db');
const{createNavigationService}=require('../navigationService');
const{createUrlMetadataService}=require('../urlMetadataService');
const{requestContentUnderstanding}=require('./openAiCompatibleProvider');

function hostname(value){try{return new URL(/^https?:\/\//i.test(String(value))?value:`https://${value}`).hostname.toLocaleLowerCase();}catch{return'';}}
function createContentIntelligenceService(db=defaultDb){const navigation=createNavigationService(db),metadata=createUrlMetadataService();
  function policies(){const configured=new Map(db.prepare('SELECT hostname,allow_content AS allowContent,updated_at_ms AS updatedAt FROM ai_domain_policies').all().map(x=>[x.hostname,x])),hosts=[...new Set(db.prepare('SELECT url FROM items').all().map(x=>hostname(x.url)).filter(Boolean))].sort();return hosts.map(host=>configured.get(host)||{hostname:host,allowContent:0,updatedAt:null});}
  function setPolicy(actor,host,allow){const value=hostname(host);if(!value)throw Object.assign(new Error('域名无效'),{code:'INVALID_DOMAIN',status:400});db.prepare('INSERT INTO ai_domain_policies(hostname,allow_content,updated_by_user_id,updated_at_ms) VALUES(?,?,?,?) ON CONFLICT(hostname) DO UPDATE SET allow_content=excluded.allow_content,updated_by_user_id=excluded.updated_by_user_id,updated_at_ms=excluded.updated_at_ms').run(value,allow?1:0,actor.id,Date.now());return policies().find(x=>x.hostname===value);}
  async function analyze(current,{actor,progress=()=>{}}){const allowed=new Set(db.prepare('SELECT hostname FROM ai_domain_policies WHERE allow_content=1').all().map(x=>x.hostname)),items=navigation.listItems(current).filter(item=>allowed.has(hostname(item.url))),findings=[],failures=[];let completed=0;progress(0,items.length);for(const item of items){try{const page=await metadata.fetchPage(item.url,{allowPrivate:actor.role==='admin',includeContent:true}),contentHash=crypto.createHash('sha256').update(page.contentText||'').digest('hex');if(item.content_hash===contentHash){completed+=1;progress(completed,items.length);continue;}const value=await requestContentUnderstanding(item,page.contentText,{actorId:actor.id});db.prepare('UPDATE items SET ai_summary=?,content_hash=?,content_analyzed_at_ms=? WHERE id=? AND scope=? AND owner_id IS ?').run(value.summary,contentHash,Date.now(),item.id,current.scope,current.ownerId);findings.push({type:'content_understood',severity:'low',title:`${item.name}：${value.summary}`,itemIds:[item.id],suggestedTags:value.tags,categorySuggestion:value.categorySuggestion});}catch(error){failures.push({id:item.id,name:item.name,code:error.code||'CONTENT_ANALYSIS_FAILED'});}completed+=1;progress(completed,items.length);}return{summary:`已分析 ${findings.length} 个网页内容，${failures.length} 个失败，${navigation.listItems(current).length-items.length} 个域名未授权`,analyzedCount:findings.length,failedCount:failures.length,findings,failures};}
  return{policies,setPolicy,analyze};}
module.exports={createContentIntelligenceService,hostname};
