import React, { useCallback, useEffect, useRef, useState } from 'react';
import { api } from '../api.js';
import { useAuth } from '../auth/AuthContext.jsx';
import { useI18n } from '../i18n/LocaleContext.jsx';
import Icon, { ContentIcon } from './Icon.jsx';
import AiCommandPanel from './AiCommandPanel.jsx';
import { possibleURL } from '../utils/urlSuggestion.js';

export default function AiAssistantWidget({ aiPersonalEnabled, activeSpace='public', launchRequest, onResourcesChanged }) {
  const auth = useAuth(); const { t, locale } = useI18n();
  const [open,setOpen]=useState(false),[tab,setTab]=useState('search'),[query,setQuery]=useState(''),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[active,setActive]=useState(-1),[viewport,setViewport]=useState(null),[operationScope,setOperationScope]=useState('personal'),[operationText,setOperationText]=useState(''),[editorVersion,setEditorVersion]=useState(0);
  const inputRef=useRef(null),triggerRef=useRef(null),requestRef=useRef(0);
  const close=useCallback(()=>{setOpen(false);triggerRef.current?.focus();},[]);
  const chooseDefaultScope=useCallback((requested)=>requested==='public'&&auth.isAdmin?'public':'personal',[auth.isAdmin]);
  const beginOperation=useCallback((scope,text='')=>{setOperationScope(chooseDefaultScope(scope));setOperationText(text);setEditorVersion(value=>value+1);setTab('operate');setOpen(true);},[chooseDefaultScope]);

  useEffect(()=>{function key(event){const shortcut=(event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k';if(shortcut&&!event.isComposing){event.preventDefault();setOpen(true);setTab('search');setTimeout(()=>inputRef.current?.focus(),0);}else if(event.key==='Escape'&&open){event.preventDefault();close();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open,close]);
  useEffect(()=>{if(!open||!window.visualViewport){setViewport(null);return;}const update=()=>{const view=window.visualViewport;setViewport({left:view.offsetLeft,top:view.offsetTop,width:view.width,height:view.height});};update();window.visualViewport.addEventListener('resize',update);window.visualViewport.addEventListener('scroll',update);return()=>{window.visualViewport.removeEventListener('resize',update);window.visualViewport.removeEventListener('scroll',update);};},[open]);
  useEffect(()=>{if(!launchRequest?.id)return;beginOperation(launchRequest.scope,launchRequest.text||'');},[launchRequest,beginOperation]);
  useEffect(()=>{if(!open||tab!=='search'||!query.trim()){setResults([]);setSearching(false);return;}const id=++requestRef.current;const timer=setTimeout(()=>{setSearching(true);api.searchItems(query.trim()).then(items=>{if(id===requestRef.current){setResults(items);setActive(items.length?0:-1);}}).catch(()=>{if(id===requestRef.current)setResults([]);}).finally(()=>{if(id===requestRef.current)setSearching(false);});},240);return()=>clearTimeout(timer);},[query,open,tab]);

  function openResult(item,position){api.clickItem(item.id,{surface:'assistant-search',viewMode:'assistant',position,eventId:`${Date.now()}-${item.id}-${Math.random().toString(36).slice(2)}`}).catch(()=>{});}
  function searchKey(event){if(event.key==='ArrowDown'){event.preventDefault();setActive(value=>Math.min(results.length-1,value+1));}if(event.key==='ArrowUp'){event.preventDefault();setActive(value=>Math.max(0,value-1));}if(event.key==='Enter'&&active>=0&&results[active]){openResult(results[active],active+1);window.open(results[active].url,'_blank','noopener,noreferrer');}}
  function createFromSearch(){const url=possibleURL(query);if(!url)return;if(!auth.authenticated){close();auth.setLoginOpen(true);return;}let name=query;try{name=new URL(url).host;}catch{/* keep query */}const scope=activeSpace==='public'&&auth.isAdmin?'public':'personal';beginOperation(scope,t('searchSuggestion.prompt',{space:t(scope==='public'?'space.public':'space.personal'),name,url}));}

  const urlSuggestion=possibleURL(query);
  const operationGate=!auth.authenticated?<div className="assistant-gate"><Icon name="user" size={36}/><h4>{t('assistant.loginTitle')}</h4><p>{t('assistant.loginDesc')}</p><button className="icon-btn primary" onClick={()=>{close();auth.setLoginOpen(true);}}>{t('auth.login')}</button></div>:auth.user.mustChangePassword?<div className="assistant-gate"><h4>{t('auth.changeRequired')}</h4></div>:operationScope==='public'&&!auth.isAdmin?<div className="assistant-gate"><Icon name="shield" size={36}/><h4>{t('auth.forbidden')}</h4></div>:operationScope==='personal'&&!aiPersonalEnabled?<div className="assistant-gate"><Icon name="assistant" size={36}/><h4>{t('assistant.disabledTitle')}</h4><p>{t('assistant.disabledDesc')}</p></div>:null;

  return <div className="ai-widget"><button ref={triggerRef} className="ai-widget-fab" onClick={()=>setOpen(value=>!value)} aria-label={t('assistant.open')}><Icon name="assistant" size={25}/><span className="shortcut-badge">⌘K</span></button>{open&&<div className="assistant-backdrop" style={viewport?{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height,right:'auto',bottom:'auto'}:undefined} onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="ai-widget-panel assistant-command" role="dialog" aria-modal="true" aria-labelledby="assistant-title"><header className="ai-widget-header"><div className="assistant-avatar"><Icon name="assistant" size={24}/></div><div><strong id="assistant-title">{t('assistant.title')}</strong><small>{t('assistant.subtitle')}</small></div><kbd>⌘/Ctrl K</kbd><button className="mini-btn" aria-label={t('common.close')} onClick={close}>×</button></header><div className="tabs ai-widget-tabs" role="tablist"><button role="tab" aria-selected={tab==='search'} className={tab==='search'?'active':''} onClick={()=>setTab('search')}><Icon name="search" size={15}/>{t('assistant.search')}</button><button role="tab" aria-selected={tab==='operate'} className={tab==='operate'?'active':''} onClick={()=>{setTab('operate');setOperationScope(chooseDefaultScope(activeSpace));}}><Icon name="assistant" size={15}/>{t('assistant.operate')}</button></div>
    {tab==='search'&&<div className="ai-widget-body assistant-body" role="tabpanel"><div className="assistant-search"><Icon name="search" size={17}/><input ref={inputRef} autoFocus aria-label={t('assistant.search')} placeholder={t(auth.authenticated?'assistant.searchAll':'assistant.searchPublic')} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={searchKey}/></div><div className="assistant-scope">{t(auth.authenticated?'assistant.scopeAll':'assistant.scopePublic')}</div><div className="ai-widget-results" role="listbox">{searching&&<div className="assistant-empty">{t('ai.searching')}</div>}{!searching&&query&&!results.length&&<div className="assistant-empty assistant-search-empty"><span>{t('ai.noResults')}</span>{urlSuggestion&&<><small>{t('searchSuggestion.url',{url:urlSuggestion})}</small><button className="icon-btn primary" onClick={createFromSearch}><Icon name="plus" size={14}/>{t('searchSuggestion.createWithAssistant')}</button></>}</div>}{results.map((item,index)=><a role="option" aria-selected={active===index} className={`assistant-result ${active===index?'active':''}`} key={`${item.scope}-${item.id}`} href={item.url} onClick={()=>openResult(item,index+1)} target="_blank" rel="noopener noreferrer"><span className="assistant-result-icon"><ContentIcon value={item.icon}/></span><span className="meta"><strong>{item.name}</strong><small>{item.categoryName||item.url}</small></span><span className={`scope-chip ${item.scope}`}>{t(item.scope==='personal'?'space.personal':'space.public')}</span></a>)}</div><div className="sr-live" aria-live="polite">{searching?t('ai.searching'):t('assistant.resultCount',{count:results.length})}</div></div>}
    {tab==='operate'&&<div className="ai-widget-body assistant-body assistant-operation-body" role="tabpanel"><div className="assistant-scope-switch"><span>{t('assistant.targetSpace')}</span><div>{auth.isAdmin&&<button className={operationScope==='public'?'active':''} onClick={()=>{setOperationScope('public');setOperationText('');setEditorVersion(value=>value+1);}}><Icon name="building" size={14}/>{t('space.public')}</button>}<button className={operationScope==='personal'?'active':''} onClick={()=>{setOperationScope('personal');setOperationText('');setEditorVersion(value=>value+1);}}><Icon name="user" size={14}/>{t('space.personal')}</button></div></div>{operationGate||<AiCommandPanel key={`${operationScope}-${editorVersion}`} scope={operationScope} initialText={operationText} compact onExecuted={result=>onResourcesChanged?.(operationScope,result)}/>}</div>}
  </section></div>}</div>;
}
