import React, { useState } from 'react';
import { api } from '../api.js';
import { useI18n } from '../i18n/LocaleContext.jsx';
import { ContentIcon } from './Icon.jsx';
const idempotencyKey=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const labels={
  'item.create':'新增资源','item.update':'更新资源','item.bulkUpdate':'批量更新资源','item.move':'移动资源','item.delete':'删除资源','category.create':'新增分类','category.update':'更新分类','category.delete':'删除分类','category.reorder':'调整分类顺序','category.move':'移动分类'
};
function operationTitle(op,locale){if(locale==='en')return op.replace('.', ' · ').replace(/\b\w/g,c=>c.toUpperCase());return labels[op]||op;}
function PreviewValue({operation}){const data=operation.display||operation.input||operation.patch||operation.preview||{};return <div className="ai-operation-data">{Object.entries(data).filter(([,value])=>value!==undefined).map(([key,value])=><div key={key}><span>{key}</span><strong>{typeof value==='object'?JSON.stringify(value):String(value)}</strong></div>)}{operation.ids&&!operation.display&&<div><span>IDs</span><strong>{operation.ids.join(', ')}</strong></div>}</div>;}
function categoryDepth(operation){if(operation.op!=='category.create')return 0;const path=operation.display?.path||operation.display?.name||'';return Math.max(0,Math.min(2,String(path).split(' / ').length-1));}
export default function AiCommandPanel({scope='personal',initialText='',onExecuted,compact=false}){const{t,locale,errorMessage}=useI18n();const[text,setText]=useState(initialText);const[plan,setPlan]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[approved,setApproved]=useState(false);const[undoing,setUndoing]=useState(false);
async function parse(){if(!text.trim())return;setLoading(true);setError('');setPlan(null);try{setPlan(await api.createAiPlan(scope,text.trim(),locale));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
async function execute(){setLoading(true);setError('');try{const result=await api.executeAiPlan(plan.id,{idempotencyKey:idempotencyKey(),confirmed:approved,confirmDestructive:approved&&plan.destructive});setPlan({...plan,status:'executed',result});onExecuted?.(result);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
async function undo(){setUndoing(true);setError('');try{await api.undoAiPlan(plan.id,idempotencyKey());setPlan({...plan,status:'undone'});onExecuted?.({status:'undone'});}catch(e){setError(errorMessage(e));}finally{setUndoing(false);}}
return <div className={`ai-command-panel ${compact?'compact':''}`}><textarea className="ai-textarea assistant-textarea" placeholder={t(scope==='personal'?'ai.personalCommandPlaceholder':'ai.publicCommandPlaceholder')} value={text} onChange={e=>setText(e.target.value)} disabled={loading}/>{error&&<div className="error-text">{error}</div>}{!plan?<button className="icon-btn primary assistant-primary" disabled={loading||!text.trim()} onClick={parse}>{t(loading?'ai.parsing':'ai.plan')}</button>:<div className="ai-plan-preview"><div className="ai-plan-summary"><strong>{locale==='en'?`${plan.operations.length} planned operations`:`计划执行 ${plan.operations.length} 项操作`}</strong><button className="text-btn" onClick={()=>{setPlan(null);setApproved(false);}}>{t('ai.reparse')}</button></div>{(plan.summary||plan.suggestions?.length>0)&&<section className="ai-planning-notes"><div className="ai-planning-title"><ContentIcon value="icon:assistant" size={18}/><div><strong>{locale==='en'?'AI planning rationale':'AI 规划思路'}</strong>{plan.summary&&<p>{plan.summary}</p>}</div></div>{plan.suggestions?.length>0&&<ul>{plan.suggestions.map((suggestion,index)=><li key={index}>{suggestion}</li>)}</ul>}</section>}<div className="ai-operation-list">{plan.operations.map((operation,index)=>{const depth=categoryDepth(operation);return <article className={`ai-operation ${operation.op==='category.create'?'category-create-operation':''} ${operation.destructive?'destructive':''}`} style={{'--operation-depth':depth}} key={index}><div className="ai-operation-heading"><span className="tag">{operationTitle(operation.op,locale)}</span>{operation.op==='category.create'&&<span className="ai-category-level">{locale==='en'?`Level ${depth+1}`:`${depth+1} 级分类`}</span>}{operation.destructive&&<strong>{locale==='en'?'Destructive':'破坏性操作'}</strong>}</div><PreviewValue operation={operation}/></article>;})}</div>{plan.status==='draft'&&<label className={`destructive-confirm plan-approval ${plan.destructive?'destructive':''}`}><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>{t(plan.destructive?'ai.approveDestructive':'ai.approvePlan')}</span></label>}<div className="modal-actions">{plan.status==='executed'?<button className="icon-btn" disabled={undoing} onClick={undo}>{locale==='en'?'Undo':'撤销'}</button>:plan.status==='undone'?<span className="tag">{locale==='en'?'Undone':'已撤销'}</span>:<button className="icon-btn primary" disabled={loading||!approved} onClick={execute}>{loading?t('ai.executing'):t('ai.confirmExecute')}</button>}</div></div>}</div>;}
