import React,{useEffect,useRef,useState}from'react';
import{api}from'../api.js';
import{useI18n}from'../i18n/LocaleContext.jsx';
import Icon,{ContentIcon}from'./Icon.jsx';
const idempotencyKey=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const labels={'item.create':'新增资源','item.update':'更新资源','item.bulkUpdate':'批量更新资源','item.move':'移动资源','item.delete':'删除资源','category.create':'新增分类','category.update':'更新分类','category.delete':'删除分类','category.reorder':'调整分类顺序','category.move':'移动分类'};
function operationTitle(op,locale){if(locale==='en')return op.replace('.',' · ').replace(/\b\w/g,c=>c.toUpperCase());return labels[op]||op;}
function PreviewValue({operation}){const data=operation.display||operation.input||operation.patch||operation.preview||{};return <div className="ai-operation-data">{Object.entries(data).filter(([,value])=>value!==undefined).map(([key,value])=><div key={key}><span>{key}</span><strong>{typeof value==='object'?JSON.stringify(value):String(value)}</strong></div>)}{operation.ids&&!operation.display&&<div><span>IDs</span><strong>{operation.ids.join(', ')}</strong></div>}</div>;}
function categoryDepth(operation){if(operation.op!=='category.create')return 0;const path=operation.display?.path||operation.display?.name||'';return Math.max(0,Math.min(2,String(path).split(' / ').length-1));}
function operationGroup(operation){return operation.destructive||operation.op.endsWith('.delete')?'danger':operation.op.startsWith('category.')?'category':'resource';}
function CategoryPlanTree({operations,locale}){const paths=[...new Set(operations.filter(item=>item.op==='category.create').map(item=>item.display?.path||item.display?.name).filter(Boolean))];if(!paths.length)return null;return <section className="ai-category-tree-preview"><header><strong>{locale==='en'?'Proposed taxonomy':'规划后的分类结构'}</strong><span>{paths.length}</span></header><div>{paths.map(path=>{const parts=String(path).split(' / ');return <div key={path} style={{'--tree-depth':Math.max(0,parts.length-1)}}><span/><strong>{parts.at(-1)}</strong><small>{parts.slice(0,-1).join(' / ')}</small></div>;})}</div></section>;}
function PlanStatus({status,locale,reapplied=false}){const executed=status==='executed';return <div className={`ai-plan-status ${status}`} role="status"><span className="ai-plan-status-icon"><Icon name={executed?'check':'undo'} size={16}/></span><div><strong>{locale==='en'?(executed?(reapplied?'Plan reapplied':'Plan executed'):'Execution undone'):(executed?(reapplied?'方案已重新应用':'方案已执行'):'方案已撤销')}</strong><small>{locale==='en'?(executed?'The approved operations have been applied.':'The changes have been reverted. You can safely reapply this plan.'):(executed?'已按授权应用本次方案中的操作':'本次变更已撤销，可以重新应用该方案')}</small></div></div>;}

export default function AiCommandPanel({scope='personal',initialText='',initialConversationId=null,initialPlan=null,onExecuted,compact=false,workspace=false,readOnly=false}){
  const{t,locale,errorMessage}=useI18n();
  const[text,setText]=useState(initialText),[plan,setPlan]=useState(initialPlan),[loading,setLoading]=useState(false),[planningStage,setPlanningStage]=useState(''),[error,setError]=useState(''),[approved,setApproved]=useState(false),[undoing,setUndoing]=useState(false),[conversationId,setConversationId]=useState(initialConversationId),[history,setHistory]=useState([]),[operationFilter,setOperationFilter]=useState('all'),planningTimers=useRef([]),autoStarted=useRef(false);
  function clearPlanningTimers(){planningTimers.current.forEach(clearTimeout);planningTimers.current=[];}
  useEffect(()=>clearPlanningTimers,[]);
  useEffect(()=>{if(workspace&&initialText&&!initialPlan&&!autoStarted.current){autoStarted.current=true;parse();}},[]);
  async function parse(){
    const prompt=text.trim();if(!prompt)return;clearPlanningTimers();setLoading(true);setPlanningStage('context');setError('');setPlan(null);planningTimers.current=[setTimeout(()=>setPlanningStage('request'),700),setTimeout(()=>setPlanningStage('slow'),15000)];
    try{let id=conversationId;if(!id){const conversation=await api.createAiConversation(scope,prompt.slice(0,60));id=conversation.id;setConversationId(id);}const value=await api.createAiPlan(scope,prompt,locale,id);setPlan(value);setHistory(current=>[...current,{role:'user',content:prompt},{role:'assistant',content:value.summary||`${value.operations.length} operations`}].slice(-8));}
    catch(e){setError(errorMessage(e));}finally{clearPlanningTimers();setPlanningStage('');setLoading(false);}
  }
  async function execute(reapply=false){setLoading(true);setError('');try{const confirmed=reapply||approved;const result=await api.executeAiPlan(plan.id,{idempotencyKey:idempotencyKey(),confirmed,confirmDestructive:confirmed&&plan.destructive});setPlan({...plan,status:'executed',result});onExecuted?.(result);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  async function undo(){setUndoing(true);setError('');try{await api.undoAiPlan(plan.id,idempotencyKey());setPlan({...plan,status:'undone'});onExecuted?.({status:'undone'});}catch(e){setError(errorMessage(e));}finally{setUndoing(false);}}
  function continueConversation(){setPlan(null);setApproved(false);setText('');}
  const counts=plan?plan.operations.reduce((value,operation)=>{value.all+=1;value[operationGroup(operation)]+=1;return value;},{all:0,category:0,resource:0,danger:0}):null,visibleOperations=plan?.operations.map((operation,index)=>({operation,index})).filter(({operation})=>operationFilter==='all'||operationGroup(operation)===operationFilter)||[];
  return <div className={`ai-command-panel ${compact?'compact':''} ${readOnly?'read-only':''}`}>
    {history.length>0&&<div className="ai-conversation-history">{history.slice(-4).map((message,index)=><div className={message.role} key={index}><span>{message.role==='user'?(locale==='en'?'You':'你'):'AI'}</span><p>{message.content}</p></div>)}</div>}
    {!workspace&&<textarea className="ai-textarea assistant-textarea" placeholder={t(scope==='personal'?'ai.personalCommandPlaceholder':'ai.publicCommandPlaceholder')} value={text} onChange={e=>setText(e.target.value)} disabled={loading}/>}
    {error&&<div className="error-text">{error}</div>}
    {loading&&!plan&&planningStage&&<div className={`ai-request-progress ${planningStage==='slow'?'slow':''}`} role="status"><span className="ai-progress-spinner"/><div><strong>{t(`ai.planningStages.${planningStage}`)}</strong><small>{t('ai.planningHint')}</small></div></div>}
    {workspace&&!plan&&!loading&&error&&<button className="icon-btn primary assistant-primary" onClick={parse}>{locale==='en'?'Retry plan':'重新生成方案'}</button>}
    {!plan?(!workspace&&<button className="icon-btn primary assistant-primary" disabled={loading||!text.trim()} onClick={parse}>{t(loading?'ai.parsing':'ai.plan')}</button>):<div className="ai-plan-preview">
      <div className="ai-plan-summary"><strong>{locale==='en'?`${plan.operations.length} planned operations`:`计划执行 ${plan.operations.length} 项操作`}</strong>{!readOnly&&<button className="text-btn" onClick={()=>{setPlan(null);setApproved(false);if(workspace)setTimeout(parse,0);}}>{t('ai.reparse')}</button>}</div>
      {(plan.summary||plan.suggestions?.length>0)&&<section className="ai-planning-notes"><div className="ai-planning-title"><ContentIcon value="icon:assistant" size={18}/><div><strong>{locale==='en'?'AI planning rationale':'AI 规划思路'}</strong>{plan.summary&&<p>{plan.summary}</p>}</div></div>{plan.suggestions?.length>0&&<ul>{plan.suggestions.map((suggestion,index)=><li key={index}>{suggestion}</li>)}</ul>}</section>}
      {workspace&&!compact&&<><div className="ai-plan-impact"><div><strong>{counts.category}</strong><span>{locale==='en'?'Category changes':'分类操作'}</span></div><div><strong>{counts.resource}</strong><span>{locale==='en'?'Resource changes':'资源操作'}</span></div><div className={counts.danger?'danger':''}><strong>{counts.danger}</strong><span>{locale==='en'?'Risky operations':'风险操作'}</span></div></div><CategoryPlanTree operations={plan.operations} locale={locale}/><div className="ai-operation-filters">{['all','category','resource','danger'].map(filter=><button className={operationFilter===filter?'active':''} key={filter} onClick={()=>setOperationFilter(filter)}>{locale==='en'?({all:'All',category:'Categories',resource:'Resources',danger:'Risk'}[filter]):({all:'全部',category:'分类',resource:'资源',danger:'风险'}[filter])}<span>{counts[filter]}</span></button>)}</div></>}
      <div className="ai-operation-list">{visibleOperations.map(({operation,index})=>{const depth=categoryDepth(operation);return <article className={`ai-operation ${operation.op==='category.create'?'category-create-operation':''} ${operation.destructive?'destructive':''}`} style={{'--operation-depth':depth}} key={index}><div className="ai-operation-heading"><span className="tag">{operationTitle(operation.op,locale)}</span>{operation.op==='category.create'&&<span className="ai-category-level">{locale==='en'?`Level ${depth+1}`:`${depth+1} 级分类`}</span>}{operation.destructive&&<strong>{locale==='en'?'Destructive':'破坏性操作'}</strong>}</div><PreviewValue operation={operation}/></article>;})}</div>
      {plan.status==='draft'&&!readOnly&&<label className={`destructive-confirm plan-approval ${plan.destructive?'destructive':''}`}><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>{t(plan.destructive?'ai.approveDestructive':'ai.approvePlan')}</span></label>}
      {(plan.status==='executed'||plan.status==='undone')&&<PlanStatus status={plan.status} locale={locale} reapplied={plan.result?.reapplied}/>}
      {!readOnly&&<div className="modal-actions">{plan.status==='executed'?<><button className="icon-btn" disabled={undoing} onClick={undo}>{locale==='en'?'Undo':'撤销'}</button>{!workspace&&<button className="icon-btn primary" onClick={continueConversation}>{locale==='en'?'Continue':'继续对话'}</button>}</>:plan.status==='undone'?<><button className="icon-btn primary" disabled={loading} onClick={()=>execute(true)}><Icon name="refresh" size={14}/>{loading?(locale==='en'?'Reapplying...':'正在重新应用...'):(locale==='en'?'Reapply':'重新应用')}</button>{!workspace&&<button className="icon-btn" onClick={continueConversation}>{locale==='en'?'Continue':'继续对话'}</button>}</>:<button className="icon-btn primary" disabled={loading||!approved} onClick={()=>execute(false)}>{loading?t('ai.executing'):t('ai.confirmExecute')}</button>}</div>}
    </div>}
  </div>;
}
