import React, { useEffect, useRef, useState } from "react";
import { api } from "../api.js";
import { useI18n } from "../i18n/LocaleContext.jsx";
import Icon from "./Icon.jsx";
import AiCommandPanel from "./AiCommandPanel.jsx";
import AiRunUsage from "./AiRunUsage.jsx";

const stageIndex = { permission:0, context:1, classify:2, report_design:2, model:2, tools:2, insight:3, plan:3, completed:3 };

const text = {
  "zh-CN": {
    title: "自然语言指令",
    description: "查询、统计和表格会立即返回真实数据；增删改会先生成待授权方案。",
    placeholder: "例如：帮我看看有多少失联链接，按分类整理成表格",
    run: "执行指令",
    running: "正在理解并查询…",
    readonly: "当前账号可以查询公共空间；修改公共空间仍需要管理员授权。",
    examples: [
      "帮我将所有链接开启探测模式",
      "帮我看看有多少失联的，按分类整理成表格",
      "查询没有标签的资源并列出名称和地址",
      "汇总当前空间各分类的资源数量",
    ],
    matched: "符合条件",
    total: "空间资源",
    online: "在线",
    offline: "失联",
    unknown: "未知",
    monitoring: "已开启探测",
    breakdown: "分组汇总",
    table: "资源明细",
    truncated: "结果较多，表格仅展示前 {count} 条；统计数字仍基于全部匹配资源。",
    enabled: "已开启",
    disabled: "未开启",
    empty: "没有找到符合条件的资源。",
    planReady: "已生成修改方案，请检查影响范围并授权后执行。",
    historyPlanReady: "该指令当时生成的操作方案",
    reportReady: "交互式报告已生成",
    reportDesc: "页面结构和图表由 AI 按指令动态设计，数据由平台受控能力实时计算。",
    openReport: "新窗口预览",
    downloadReport: "下载 HTML",
    historyTitle: "指令执行记录",
    historyDesc: "历史记录仅用于查看当时的输入和执行结果，不能再次提交或执行。",
    promptLabel: "原始指令",
    historyPreview: "只读预览",
    failed: "指令执行失败",
    elapsed: "已用时 {seconds} 秒",
    progress: ["正在识别指令与目标空间", "正在检查权限并准备上下文", "正在调用 AI 与平台能力", "正在整理结果与审计记录"],
    cancel: "取消执行",
    cancelled: "本次指令已取消",
  },
  en: {
    title: "Natural-language command",
    description: "Queries, counts, and tables return real data immediately. Mutations become an approval plan.",
    placeholder: "Example: Find offline links and organize them into a table by category",
    run: "Run command",
    running: "Understanding and querying…",
    readonly: "You can query Public Space. Mutations still require an administrator.",
    examples: [
      "Enable monitoring for every link",
      "Find offline links and group them by category in a table",
      "List resources without tags",
      "Summarize resource counts by category",
    ],
    matched: "Matched",
    total: "Workspace total",
    online: "Online",
    offline: "Offline",
    unknown: "Unknown",
    monitoring: "Monitoring enabled",
    breakdown: "Breakdown",
    table: "Resource details",
    truncated: "The table shows the first {count} rows. Metrics still use all matches.",
    enabled: "Enabled",
    disabled: "Disabled",
    empty: "No matching resources were found.",
    planReady: "A mutation plan is ready. Review its scope and authorize it before execution.",
    historyPlanReady: "Operation plan generated by this command",
    reportReady: "Interactive report generated",
    reportDesc: "AI designs the layout and charts for your request; governed platform tools calculate the live data.",
    openReport: "Open preview",
    downloadReport: "Download HTML",
    historyTitle: "Command record",
    historyDesc: "History is a read-only snapshot of the original command and result. It cannot be submitted again.",
    promptLabel: "Original command",
    historyPreview: "Read-only preview",
    failed: "Command failed",
    elapsed: "Elapsed {seconds}s",
    progress: ["Identifying the command and target space", "Checking permissions and preparing context", "Calling AI and governed platform tools", "Formatting the result and audit record"],
    cancel: "Cancel",
    cancelled: "This command was cancelled",
  },
};

function compactValue(column, row, c) {
  const value=row[column.key];
  if(column.key==="url"&&value)return <a href={value} target="_blank" rel="noreferrer" title={value}>{value}</a>;
  if(column.key==="status")return <span className={`ai-query-status ${value||"unknown"}`}>{value||c.unknown}</span>;
  if(column.key==="checkEnabled")return value?c.enabled:c.disabled;
  if(Array.isArray(value))return value.join(", ")||"—";
  return value===0||value===false?String(value):(value||"—");
}

function CompactQueryResult({ result, c, metrics }) {
  const columns = Array.isArray(result.columns) ? result.columns : [];
  const rows = Array.isArray(result.rows) ? result.rows : [];
  const primary = columns.find(column => ["name", "title"].includes(column.key))
    || columns.find(column => column.key !== "url")
    || columns[0];
  const details = columns.filter(column => column.key !== primary?.key).slice(0, 5);
  return <section className="assistant-query-result">
    <header><span><Icon name="insights" size={18}/></span><div><strong>{result.title}</strong><p>{result.answer}</p></div></header>
    <div className="assistant-query-metrics">{metrics.map(([key, label]) => <div className={key} key={key}><span>{label}</span><strong>{result.summary?.[key] ?? 0}</strong></div>)}</div>
    {result.breakdown?.length > 0 && <div className="assistant-query-groups"><span>{c.breakdown}</span><div>{result.breakdown.slice(0, 12).map((item, index) => <span key={`${item.name}-${index}`} title={item.name}>{item.name}<strong>{item.count}</strong></span>)}</div></div>}
    {rows.length > 0 ? <div className="assistant-query-list">
      <header><strong>{c.table}</strong><span>{rows.length}</span></header>
      <div>{rows.map((row, index) => <article key={row.id ?? index}>
        <div className="assistant-query-row-title"><strong title={String(row[primary?.key] || "")}>{compactValue(primary || { key:"name" }, row, c)}</strong>{row.status && primary?.key !== "status" && <span className={`ai-query-status ${row.status}`}>{row.status}</span>}</div>
        {details.length > 0 && <dl>{details.map(column => <div className={column.key === "url" ? "url" : ""} key={column.key}><dt>{column.label}</dt><dd>{compactValue(column, row, c)}</dd></div>)}</dl>}
      </article>)}</div>
      {result.truncated && <p>{c.truncated.replace("{count}", rows.length)}</p>}
    </div> : <div className="ai-query-empty">{c.empty}</div>}
  </section>;
}

function QueryResult({ result, locale, compact = false }) {
  const c = text[locale] || text["zh-CN"];
  const metrics = [
    ["matched", c.matched],
    ["total", c.total],
    ["online", c.online],
    ["offline", c.offline],
    ["unknown", c.unknown],
    ["monitoringEnabled", c.monitoring],
  ];
  if(compact)return <CompactQueryResult result={result} c={c} metrics={metrics}/>;
  return <div className="ai-query-result">
    <header><span><Icon name="insights" size={20}/></span><div><strong>{result.title}</strong><p>{result.answer}</p></div></header>
    <div className="ai-query-metrics">{metrics.map(([key,label])=><div className={key} key={key}><strong>{result.summary?.[key] ?? 0}</strong><span>{label}</span></div>)}</div>
    {result.breakdown?.length>0&&<section className="ai-query-breakdown"><h3>{c.breakdown}</h3><div>{result.breakdown.map(item=><div key={item.name}><span title={item.name}>{item.name}</span><strong>{item.count}</strong></div>)}</div></section>}
    {result.rows?.length>0?<section className="ai-query-table-section"><h3>{c.table}<span>{result.rows.length}</span></h3><div className="ai-query-table-scroll"><table><thead><tr>{result.columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.id}>{result.columns.map(column=><td key={column.key}>{column.key==="url"?<a href={row.url} target="_blank" rel="noreferrer" title={row.url}>{row.url}</a>:column.key==="status"?<span className={`ai-query-status ${row.status}`}>{row.status}</span>:column.key==="checkEnabled"?(row.checkEnabled?c.enabled:c.disabled):(row[column.key]||"—")}</td>)}</tr>)}</tbody></table></div>{result.truncated&&<p className="ai-query-truncated">{c.truncated.replace("{count}",result.rows.length)}</p>}</section>:<div className="ai-query-empty">{c.empty}</div>}
  </div>;
}

function ReportResult({ result, locale, compact = false }) {
  const c = text[locale] || text["zh-CN"], report = result.report;
  const previewUrl = `${report.previewUrl}${locale === "en" ? "?locale=en" : ""}`;
  const downloadUrl = `${report.downloadUrl}${locale === "en" ? "&locale=en" : ""}`;
  if(compact)return <section className="assistant-report-result"><header><span><Icon name="insights" size={19}/></span><div><strong>{report.title||c.reportReady}</strong><p>{c.reportDesc}</p></div></header><div className="assistant-report-summary"><div><strong>{report.metrics?.resources||0}</strong><span>{c.total}</span></div><div><strong>{report.metrics?.categories||0}</strong><span>{locale==="en"?"Categories":"分类"}</span></div><div><strong>{report.metrics?.monitoringRate||0}%</strong><span>{c.monitoring}</span></div><div><strong>{report.spaces?.length||0}</strong><span>{locale==="en"?"Spaces":"空间"}</span></div></div><div className="assistant-report-actions"><a className="icon-btn" href={previewUrl} target="_blank" rel="noreferrer"><Icon name="globe" size={14}/>{c.openReport}</a><a className="icon-btn primary" href={downloadUrl}><Icon name="docs" size={14}/>{c.downloadReport}</a></div></section>;
  return <section className="ai-report-result">
    <header><div><span><Icon name="insights" size={20}/></span><div><strong>{report.title || c.reportReady}</strong><p>{c.reportDesc}</p></div></div><div><a className="icon-btn" href={previewUrl} target="_blank" rel="noreferrer"><Icon name="globe" size={14}/>{c.openReport}</a><a className="icon-btn primary" href={downloadUrl}><Icon name="docs" size={14}/>{c.downloadReport}</a></div></header>
    <div className="ai-report-summary"><div><strong>{report.metrics?.resources || 0}</strong><span>{c.total}</span></div><div><strong>{report.metrics?.categories || 0}</strong><span>{locale === "en" ? "Categories" : "分类"}</span></div><div><strong>{report.metrics?.monitoringRate || 0}%</strong><span>{c.monitoring}</span></div><div><strong>{report.spaces?.length || 0}</strong><span>{locale === "en" ? "Spaces" : "空间"}</span></div></div>
    <iframe title={report.title || c.reportReady} src={previewUrl} sandbox="allow-scripts allow-popups"/>
  </section>;
}

function InstructionProgress({ stage, elapsed, locale, run, onCancel }) {
  const c = text[locale] || text["zh-CN"];
  return <section className="ai-instruction-progress" role="status" aria-live="polite">
    <div className="ai-instruction-progress-head"><span className="ai-instruction-orbit"><i/><i/><i/></span><div><strong>{c.progress[stage]}</strong><small>{c.elapsed.replace("{seconds}", Math.max(1, elapsed))}</small></div><button type="button" className="text-btn" onClick={onCancel}>{c.cancel}</button></div>
    <div className="ai-instruction-progress-bar"><span/></div>
    <ol>{c.progress.map((label,index)=><li className={index<stage?"completed":index===stage?"active":""} key={label}><span>{index<stage?<Icon name="check" size={10}/>:index+1}</span><small>{label}</small></li>)}</ol>
    <AiRunUsage run={run} locale={locale} live compact/>
  </section>;
}

function ErrorResult({ result, locale }) {
  const c = text[locale] || text["zh-CN"];
  return <section className="ai-instruction-error-preview"><span><Icon name="shield" size={17}/></span><div><strong>{c.failed}</strong><p>{result.error || result.message || c.failed}</p>{result.code&&<small>{result.code}</small>}</div></section>;
}

export default function AiInstructionPanel({ scope, canMutate = true, initialRecord = null, initialText = "", contextText = "", compact = false, quick = false, onDraftChange, onCreated, onExecuted }) {
  const { locale, errorMessage } = useI18n();
  const c = text[locale] || text["zh-CN"];
  const historyMode = Boolean(initialRecord);
  const [draft, setDraft] = useState(initialRecord?.prompt || initialText || "");
  const [busy, setBusy] = useState(false);
  const [busyStage, setBusyStage] = useState(0);
  const [elapsed, setElapsed] = useState(0);
  const [runUsage, setRunUsage] = useState(initialRecord?.result?.run || null);
  const [error, setError] = useState("");
  const [result, setResult] = useState(initialRecord?.result || null);
  const controllerRef = useRef(null);

  useEffect(() => {
    if (!busy) return undefined;
    const started = Date.now();
    setBusyStage(0);
    setElapsed(0);
    const elapsedTimer = setInterval(() => setElapsed(Math.floor((Date.now() - started) / 1000)), 500);
    return () => clearInterval(elapsedTimer);
  }, [busy]);
  useEffect(() => () => controllerRef.current?.abort(), []);

  async function run() {
    const value = draft.trim();
    if (!value || busy || historyMode) return;
    setBusy(true);
    setError("");
    setResult(null);
    setRunUsage(null);
    const controller = new AbortController();controllerRef.current=controller;
    try {
      const execute=quick?api.runAiQuickInstructionStream:api.runAiInstructionStream;
      const instruction=contextText?`${contextText}\n\n${locale==="en"?"User command":"用户指令"}: ${value}`:value;
      const response=await execute(scope, instruction, locale, null, {
        signal:controller.signal,
        onStage:event=>setBusyStage(stageIndex[event.stage] ?? 2),
        onUsage:event=>setRunUsage(event.run),
        onTools:event=>setRunUsage(event.run),
      });
      const finalResult=response.result || null;
      if(finalResult){setResult(finalResult);setRunUsage(finalResult.run || response.run || null);onCreated?.(finalResult.conversationId);}
    } catch (reason) {
      setError(reason?.name==="AbortError"?c.cancelled:errorMessage(reason));
    } finally {
      if(controllerRef.current===controller)controllerRef.current=null;
      setBusy(false);
    }
  }

  return <section className={`ai-instruction-panel ${compact?"compact":""}`}>
    <header><div><span className="ai-step-number"><Icon name={historyMode?"docs":"tools"} size={15}/></span><div><strong>{historyMode?c.historyTitle:c.title}</strong><small>{historyMode?c.historyDesc:c.description}</small></div></div><span className="ai-instruction-safety"><Icon name="shield" size={13}/>{historyMode?c.historyPreview:canMutate?(locale==="en"?"Mutations require approval":"修改需授权"):(locale==="en"?"Read only":"只读模式")}</span></header>
    <div className="ai-instruction-body">
      {historyMode?<section className="ai-instruction-history-prompt"><span><Icon name="tools" size={15}/>{c.promptLabel}</span><p>{initialRecord.prompt}</p>{initialRecord.updatedAt&&<time>{new Date(initialRecord.updatedAt).toLocaleString(locale)}</time>}</section>:<div className="ai-instruction-composer">
        {compact&&<div className="assistant-editor-toolbar"><span><Icon name="edit" size={14}/>{locale==="en"?"New command":"新指令"}</span><small>{draft.length} {locale==="en"?"characters":"字"}</small></div>}
        <textarea autoFocus={compact} value={draft} disabled={busy} placeholder={c.placeholder} onChange={event=>{setDraft(event.target.value);onDraftChange?.(event.target.value);}} onKeyDown={event=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter")run();}}/>
        <div className="ai-instruction-examples">{compact&&<span className="assistant-example-label"><Icon name="bolt" size={12}/>{locale==="en"?"Try":"快捷示例"}</span>}{c.examples.map(example=><button type="button" key={example} onClick={()=>{setDraft(example);onDraftChange?.(example);}}>{example}</button>)}</div>
        {!canMutate&&<p className="ai-instruction-readonly"><Icon name="shield" size={13}/>{c.readonly}</p>}
        {error&&<div className="error-text">{error}</div>}
        <div className="ai-instruction-submit"><small>Ctrl/⌘ + Enter</small><button className="icon-btn primary" disabled={busy||!draft.trim()} onClick={run}><Icon name={busy?"refresh":"assistant"} className={busy?"ai-spin":""} size={14}/>{busy?c.progress[busyStage]:c.run}</button></div>
      </div>}
      {busy&&<InstructionProgress stage={busyStage} elapsed={elapsed} locale={locale} run={runUsage} onCancel={()=>controllerRef.current?.abort()}/>} 
      {result?.kind==="query"&&<QueryResult result={result} locale={locale} compact={compact}/>} 
      {result?.kind==="report"&&<ReportResult result={result} locale={locale} compact={compact}/>} 
      {result?.kind==="plan"&&<div className="ai-instruction-plan"><p><Icon name="check" size={15}/>{historyMode?c.historyPlanReady:c.planReady}</p><AiCommandPanel scope={scope} initialPlan={result.plan} workspace compact={compact} readOnly={historyMode} onExecuted={onExecuted}/></div>}
      {result?.kind==="error"&&<ErrorResult result={result} locale={locale}/>} 
      {!busy&&(result?.run||runUsage)&&<AiRunUsage run={result?.run||runUsage} locale={locale} compact={compact}/>} 
    </div>
  </section>;
}
