import React, { useState } from 'react';
import { useAuth } from '../auth/AuthContext.jsx';
import { useI18n } from '../i18n/LocaleContext.jsx';
import { useToast } from './ToastProvider.jsx';
import DropdownMenu from './DropdownMenu.jsx';
import Icon from './Icon.jsx';
import UserProfileModal from './UserProfileModal.jsx';

function PasswordField({ value, onChange, placeholder, autoComplete }) {
  const { t } = useI18n(); const [visible, setVisible] = useState(false);
  return <div className="password-field"><input type={visible ? 'text' : 'password'} autoComplete={autoComplete} placeholder={placeholder} value={value} onChange={onChange}/><button type="button" className="password-eye" aria-label={t(visible ? 'auth.hidePassword' : 'auth.showPassword')} title={t(visible ? 'auth.hidePassword' : 'auth.showPassword')} onClick={()=>setVisible((v)=>!v)}>{visible ? <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3l18 18"/><path d="M10.6 10.7a2 2 0 0 0 2.7 2.7"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5.5 0 9 5 9 8a11.8 11.8 0 0 1-2 3.5M6.6 6.6C4.4 8 3 10.2 3 12c0 3 3.5 8 9 8a10.7 10.7 0 0 0 4.1-.8"/></svg> : <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12s3.5-8 9-8 9 8 9 8-3.5 8-9 8-9-8-9-8Z"/><circle cx="12" cy="12" r="3"/></svg>}</button></div>;
}

export function LoginDialog() {
  const auth=useAuth();const {t,errorMessage}=useI18n();const toast=useToast();const [mode,setMode]=useState('login');const [form,setForm]=useState({username:'',displayName:'',password:'',confirm:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  if(!auth.loginOpen)return null;
  async function submit(event){event.preventDefault();setError('');if(mode==='register'&&form.password!==form.confirm){setError(t('auth.passwordMismatch'));return;}setLoading(true);try{if(mode==='login'){await auth.login(form.username,form.password);toast.show(t('toast.loginSuccess'));}else{await auth.register({username:form.username,displayName:form.displayName,password:form.password});toast.show(t('toast.registerSuccess'));}}catch(e){const message=errorMessage(e);setError(message);toast.show(message,'error');}finally{setLoading(false);}}
  return <div className="modal-mask" role="presentation"><div className="modal auth-dialog" role="dialog" aria-modal="true"><div className="auth-mode"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>{t('auth.login')}</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>{t('auth.register')}</button></div><h3>{t(mode==='login'?'auth.login':'auth.register')}</h3><p className="modal-sub">{t(mode==='login'?'auth.loginDesc':'auth.registerDesc')}</p><form onSubmit={submit}><div className="form-row"><label>{t('auth.username')}</label><input autoFocus autoComplete="username" placeholder={t('auth.usernamePlaceholder')} value={form.username} onChange={(e)=>setForm({...form,username:e.target.value})}/><div className="hint">{t('auth.usernameHint')}</div></div>{mode==='register'&&<div className="form-row"><label>{t('auth.displayName')}</label><input placeholder={t('auth.displayNamePlaceholder')} value={form.displayName} onChange={(e)=>setForm({...form,displayName:e.target.value})}/></div>}<div className="form-row"><label>{t('auth.password')}</label><PasswordField autoComplete={mode==='login'?'current-password':'new-password'} placeholder={t('auth.passwordPlaceholder')} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/>{mode==='register'&&<div className="hint">{t('auth.passwordHint')}</div>}</div>{mode==='register'&&<div className="form-row"><label>{t('auth.confirmPassword')}</label><PasswordField autoComplete="new-password" placeholder={t('auth.confirmPasswordPlaceholder')} value={form.confirm} onChange={(e)=>setForm({...form,confirm:e.target.value})}/></div>}{error&&<div className="error-text">{error}</div>}<div className="modal-actions"><button type="button" className="icon-btn" onClick={()=>auth.setLoginOpen(false)}>{t('common.cancel')}</button><button className="icon-btn primary" disabled={loading}>{loading?t(mode==='login'?'auth.loggingIn':'auth.registering'):t(mode==='login'?'auth.login':'auth.register')}</button></div></form></div></div>;
}
export function PasswordChangeDialog(){const auth=useAuth();const{t,errorMessage}=useI18n();const toast=useToast();const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);if(!auth.user?.mustChangePassword)return null;async function submit(event){event.preventDefault();setLoading(true);setError('');try{await auth.changePassword(current,next);toast.show(t('toast.passwordChanged'));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}return <div className="modal-mask"><div className="modal auth-dialog" role="dialog" aria-modal="true"><h3>{t('auth.changeRequired')}</h3><p className="modal-sub">{t('auth.changeRequiredDesc')}</p><form onSubmit={submit}><div className="form-row"><label>{t('auth.currentPassword')}</label><PasswordField placeholder={t('auth.passwordPlaceholder')} value={current} onChange={(e)=>setCurrent(e.target.value)}/></div><div className="form-row"><label>{t('auth.newPassword')}</label><PasswordField placeholder={t('auth.passwordPlaceholder')} value={next} onChange={(e)=>setNext(e.target.value)}/></div>{error&&<div className="error-text">{error}</div>}<div className="modal-actions"><button className="icon-btn primary" disabled={loading}>{loading?t('common.saving'):t('auth.changePassword')}</button></div></form></div></div>;}
export function AccountMenu(){const auth=useAuth();const{t,locale}=useI18n();const[profileOpen,setProfileOpen]=useState(false);if(auth.loading)return <span className="account-loading"/>;if(!auth.user)return <button className="icon-btn square-icon" aria-label={t('auth.login')} title={t('auth.login')} onClick={()=>auth.setLoginOpen(true)}><Icon name="user" size={18}/></button>;const avatar=auth.user.avatarUrl?<img className="account-avatar-image" src={auth.user.avatarUrl} alt=""/>:<Icon name="user" size={18}/>;return <>{<DropdownMenu className="account-menu" menuClassName="account-dropdown" trigger={<button className="icon-btn square-icon" aria-label={auth.user.displayName} title={auth.user.displayName}>{avatar}</button>}><div className="account-dropdown-header"><strong>{auth.user.displayName}</strong><small>@{auth.user.username}</small></div><button role="menuitem" onClick={()=>setProfileOpen(true)}><Icon name="settings" size={15}/>{locale==='en'?'Account settings':'个人账户设置'}</button>{auth.isAdmin&&<button role="menuitem" onClick={()=>{location.href='/admin';}}>{t('auth.adminWorkspace')}</button>}<button role="menuitem" onClick={auth.logout}>{t('auth.logout')}</button></DropdownMenu>}{profileOpen&&<UserProfileModal onClose={()=>setProfileOpen(false)}/>}</>}
