import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useI18n } from '../i18n/LocaleContext.jsx';
import Icon, { ContentIcon } from './Icon.jsx';
import CategoryTree from './CategoryTree.jsx';
import CategorySelectionBox from './CategorySelectionBox.jsx';
import { CATEGORY_SIDEBAR_MAX_WIDTH, CATEGORY_SIDEBAR_MIN_WIDTH, categorySidebarCollapsePreview, clampCategorySidebarWidth } from '../utils/categorySidebar.js';

export default function CategoryNav({ categories, counts, active, onSelect, favoriteCount=0, favoriteActive=false, onSelectFavorites, manageable=false, onCreate, onRename, onChangeIcon, onAccess, onDelete, onDropItems, onMoveCategory, selectionStates, onToggleSelection, selectionDisabled=false, resizable=false, collapsed=false, onCollapsedChange, onWidthChange, onWidthReset }) {
  const { t, locale } = useI18n();
  const navRef=useRef(null),dragRef=useRef(null),mobileTriggerRef=useRef(null),mobileSheetRef=useRef(null),mobileHistoryRef=useRef(false),mobileDragRef=useRef(null),[collapsePreview,setCollapsePreview]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[mobileDrag,setMobileDrag]=useState(0);
  const totalCount = counts.all ?? Object.values(counts).reduce((a, b) => a + b, 0);
  const activeCategory=useMemo(()=>categories.find(category=>category.id===active),[active,categories]);
  const activeName=favoriteActive?t('category.favorites'):active==='all'?t('category.all'):active==='uncategorized'?t('category.uncategorized'):activeCategory?.path_label||activeCategory?.name||t('category.all');
  const activeCount=favoriteActive?favoriteCount:active==='all'?totalCount:active==='uncategorized'?(counts.uncategorized||0):(counts[active]||0);
  const activeIcon=favoriteActive?'icon:star':active==='all'?'icon:grid':active==='uncategorized'?'icon:archive':activeCategory?.icon||'icon:folder';
  const selectable=Boolean(selectionStates&&onToggleSelection);
  const selectionLabel=(key,name)=>t(selectionStates?.[key]==='all'?'batch.unselectCategory':'batch.selectCategory',{name});
  function dropUncategorized(event){if(!manageable||!onDropItems)return;event.preventDefault();onDropItems(event,null);}
  const resize=(value)=>onWidthChange?.(clampCategorySidebarWidth(value));
  const pointerDown=(event)=>{if(collapsed)return;event.preventDefault();event.currentTarget.setPointerCapture?.(event.pointerId);dragRef.current={pointerId:event.pointerId,x:event.clientX,width:navRef.current?.getBoundingClientRect().width||CATEGORY_SIDEBAR_MIN_WIDTH,collapsePreview:false};setCollapsePreview(false);document.body.classList.add('category-sidebar-resizing');};
  const pointerMove=(event)=>{const drag=dragRef.current;if(!drag||drag.pointerId!==event.pointerId)return;const rawWidth=drag.width+event.clientX-drag.x,nextPreview=categorySidebarCollapsePreview(rawWidth,drag.collapsePreview);drag.collapsePreview=nextPreview;setCollapsePreview(nextPreview);if(!nextPreview)resize(rawWidth);};
  const finishPointer=(event,allowCollapse)=>{const drag=dragRef.current;if(drag?.pointerId!==event.pointerId)return;dragRef.current=null;setCollapsePreview(false);document.body.classList.remove('category-sidebar-resizing');event.currentTarget.releasePointerCapture?.(event.pointerId);if(allowCollapse&&drag.collapsePreview)onCollapsedChange?.(true);};
  const pointerUp=(event)=>finishPointer(event,true),pointerCancel=(event)=>finishPointer(event,false);
  const keyResize=(event)=>{const current=navRef.current?.getBoundingClientRect().width||CATEGORY_SIDEBAR_MIN_WIDTH;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();resize(current+(event.key==='ArrowRight'?12:-12));}else if(event.key==='Home'){event.preventDefault();resize(CATEGORY_SIDEBAR_MIN_WIDTH);}else if(event.key==='End'){event.preventDefault();resize(CATEGORY_SIDEBAR_MAX_WIDTH);}};
  const collapseLabel=collapsed?(locale==='en'?'Expand categories':'展开分类栏'):(locale==='en'?'Collapse categories':'收起分类栏');
  const mobileTitle=locale==='en'?'Choose a category':'选择分类';
  const openMobile=()=>{if(mobileOpen)return;mobileHistoryRef.current=true;history.pushState({...history.state,navpilotCategoryDrawer:true},'');setMobileOpen(true);};
  const closeMobile=(useHistory=true)=>{setMobileOpen(false);setMobileDrag(0);if(useHistory&&mobileHistoryRef.current&&history.state?.navpilotCategoryDrawer){mobileHistoryRef.current=false;history.back();}else mobileHistoryRef.current=false;setTimeout(()=>mobileTriggerRef.current?.focus(),0);};
  const selectCategory=(value,mobile=false)=>{onSelect(value);if(mobile){closeMobile();requestAnimationFrame(()=>{const content=document.querySelector('.main-layout>.content');if(!content)return;const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;window.scrollTo?.({top:Math.max(0,content.getBoundingClientRect().top+window.scrollY-8),behavior:reduced?'auto':'smooth'});});}};
  const selectFavorites=mobile=>{onSelectFavorites?.();if(mobile){closeMobile();requestAnimationFrame(()=>{const content=document.querySelector('.main-layout>.content');if(!content)return;const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;window.scrollTo?.({top:Math.max(0,content.getBoundingClientRect().top+window.scrollY-8),behavior:reduced?'auto':'smooth'});});}};
  useEffect(()=>{if(!mobileOpen)return undefined;const previousOverflow=document.body.style.overflow,previousOverscroll=document.body.style.overscrollBehavior;document.body.style.overflow='hidden';document.body.style.overscrollBehavior='none';setTimeout(()=>mobileSheetRef.current?.querySelector('button')?.focus(),0);const key=event=>{if(event.key==='Escape'){event.preventDefault();closeMobile();return;}if(event.key==='Tab'){const focusable=[...(mobileSheetRef.current?.querySelectorAll('button:not(:disabled),[href],input:not(:disabled),[tabindex]:not([tabindex="-1"])')||[])];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}},pop=()=>{mobileHistoryRef.current=false;setMobileOpen(false);setMobileDrag(0);setTimeout(()=>mobileTriggerRef.current?.focus(),0);},media=window.matchMedia?.('(max-width: 760px)'),change=event=>{if(!event.matches)closeMobile();};window.addEventListener('keydown',key);window.addEventListener('popstate',pop);media?.addEventListener?.('change',change);return()=>{document.body.style.overflow=previousOverflow;document.body.style.overscrollBehavior=previousOverscroll;window.removeEventListener('keydown',key);window.removeEventListener('popstate',pop);media?.removeEventListener?.('change',change);};},[mobileOpen]);
  const startMobileDrag=event=>{mobileDragRef.current={pointerId:event.pointerId,y:event.clientY};event.currentTarget.setPointerCapture?.(event.pointerId);};
  const moveMobileDrag=event=>{const drag=mobileDragRef.current;if(!drag||drag.pointerId!==event.pointerId)return;setMobileDrag(Math.max(0,event.clientY-drag.y));};
  const finishMobileDrag=event=>{const drag=mobileDragRef.current;if(!drag||drag.pointerId!==event.pointerId)return;const distance=Math.max(0,event.clientY-drag.y);mobileDragRef.current=null;event.currentTarget.releasePointerCapture?.(event.pointerId);if(distance>72)closeMobile();else setMobileDrag(0);};
  const categoryBody=mobile=><div className="category-nav-body">
      <button className={!favoriteActive&&active === 'all' ? 'active' : ''} onClick={() => selectCategory('all',mobile)}>{selectable&&<CategorySelectionBox state={selectionStates.all} label={selectionLabel('all',t('category.all'))} disabled={selectionDisabled||!totalCount} onToggle={()=>onToggleSelection('all')}/>}<span className="cat-icon"><ContentIcon value="icon:grid" size={17} /></span><span className="category-nav-name" title={t('category.all')}>{t('category.all')}</span><span className="count">{totalCount}</span></button>
      {favoriteCount>0&&<><button className={`category-nav-favorite ${favoriteActive?'active':''}`} aria-current={favoriteActive?'page':undefined} onClick={()=>selectFavorites(mobile)}>{selectable&&<span className="category-selection-spacer" aria-hidden="true"/>}<span className="cat-icon"><ContentIcon value="icon:star" size={17}/></span><span className="category-nav-name" title={t('category.favorites')}>{t('category.favorites')}</span><span className="count">{favoriteCount}</span></button><span className="category-nav-primary-divider" aria-hidden="true"/></>}
      <CategoryTree categories={categories} counts={counts} active={active} onSelect={value=>selectCategory(value,mobile)} manageable={manageable} onCreate={onCreate} onRename={onRename} onChangeIcon={onChangeIcon} onAccess={onAccess} onDelete={onDelete} onDropItems={onDropItems} onMoveCategory={onMoveCategory} selectionStates={selectionStates} onToggleSelection={onToggleSelection} selectionDisabled={selectionDisabled}/>
      <button className={active === 'uncategorized' ? 'active' : ''} onClick={() => selectCategory('uncategorized',mobile)} onDragOver={event=>{if(manageable){event.preventDefault();event.dataTransfer.dropEffect='move';event.currentTarget.classList.add('drop-target');}}} onDragLeave={event=>event.currentTarget.classList.remove('drop-target')} onDrop={event=>{event.currentTarget.classList.remove('drop-target');dropUncategorized(event);}}>{selectable&&<CategorySelectionBox state={selectionStates.uncategorized} label={selectionLabel('uncategorized',t('category.uncategorized'))} disabled={selectionDisabled||!(counts.uncategorized||0)} onToggle={()=>onToggleSelection('uncategorized')}/>}<span className="cat-icon"><ContentIcon value="icon:archive" size={17} /></span><span className="category-nav-name" title={t('category.uncategorized')}>{t('category.uncategorized')}</span><span className="count">{counts.uncategorized || 0}</span></button>
    </div>;
  return <>
    <button ref={mobileTriggerRef} type="button" className="category-nav-mobile-trigger" onClick={openMobile} aria-haspopup="dialog" aria-expanded={mobileOpen}><span className="cat-icon"><ContentIcon value={activeIcon} size={18}/></span><span><small>{locale==='en'?'Current category':'当前分类'}</small><strong>{activeName}</strong></span><em>{activeCount}</em><Icon name="chevronDown" size={16}/></button>
    <nav ref={navRef} className={`category-nav ${resizable?'resizable':''} ${collapsed?'collapsed':''} ${collapsePreview?'collapse-preview':''}`} aria-label={t('category.manage')}>
    {resizable&&<button type="button" className="category-nav-resize-toggle" onClick={()=>onCollapsedChange?.(!collapsed)} aria-label={collapseLabel} title={collapseLabel}><Icon name={collapsed?'chevronRight':'chevronLeft'} size={14}/><span>{collapsed?'':locale==='en'?'Collapse':'收起'}</span></button>}
    <div aria-hidden={collapsed||undefined}>{categoryBody(false)}</div>
    {collapsePreview&&<div className="category-nav-collapse-hint" role="status"><Icon name="chevronLeft" size={14}/><span>{locale==='en'?'Release to collapse':'松开即可收起'}</span></div>}
    {resizable&&!collapsed&&(
      <div className="category-nav-resizer" role="separator" tabIndex="0" aria-orientation="vertical" aria-label={locale==='en'?'Resize category sidebar':'调整分类栏宽度'} aria-valuemin={CATEGORY_SIDEBAR_MIN_WIDTH} aria-valuemax={CATEGORY_SIDEBAR_MAX_WIDTH} aria-valuenow={Math.round(navRef.current?.getBoundingClientRect().width||CATEGORY_SIDEBAR_MIN_WIDTH)} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerCancel} onKeyDown={keyResize} onDoubleClick={()=>onWidthReset?.()}/>
    )}
  </nav>
  {mobileOpen&&createPortal(<div className="category-mobile-backdrop" onPointerDown={event=>event.target===event.currentTarget&&closeMobile()}><section ref={mobileSheetRef} className="category-mobile-sheet" role="dialog" aria-modal="true" aria-label={mobileTitle} style={{'--mobile-sheet-drag':`${mobileDrag}px`}}><header onPointerDown={startMobileDrag} onPointerMove={moveMobileDrag} onPointerUp={finishMobileDrag} onPointerCancel={finishMobileDrag}><i/><div><strong>{mobileTitle}</strong><small>{locale==='en'?`${totalCount} resources in this space`:`当前空间共 ${totalCount} 个资源`}</small></div><button type="button" aria-label={t('common.close')} onPointerDown={event=>event.stopPropagation()} onClick={()=>closeMobile()}><Icon name="close" size={18}/></button></header><div className="category-mobile-sheet-body"><nav className="category-nav category-nav-mobile" aria-label={t('category.manage')}>{categoryBody(true)}</nav></div></section></div>,document.body)}
  </>;
}
