import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../api.js';
import { useI18n } from '../i18n/LocaleContext.jsx';
import CategoryNav from './CategoryNav.jsx';
import NavCard from './NavCard.jsx';
import ItemFormModal from './ItemFormModal.jsx';
import AiAddModal from './AiAddModal.jsx';
import ViewModeSwitcher from './ViewModeSwitcher.jsx';
import Icon, { ContentIcon } from './Icon.jsx';
import { categoryCounts, filterByCategory } from '../utils/categoryTree.js';

const validView=(value)=>{const migrated=['dense','board'].includes(value)?'overview':value;return ['card','compact','overview'].includes(migrated)?migrated:'card';};

export function DeleteCategoryDialog({ impact, onCancel, onConfirm }) {
  const { t }=useI18n(); const [deleting,setDeleting]=useState(false);
  return <div className="modal-mask" onClick={onCancel}><div className="modal category-delete-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-category-title" onClick={e=>e.stopPropagation()}><h3 id="delete-category-title">{t('category.deleteTitle')}</h3><p className="modal-sub">{t('category.deleteImpact',{name:impact.category.pathLabel||impact.category.name,categories:impact.categoryCount,resources:impact.resourceCount})}</p><div className="settings-warning"><Icon name="shield" size={17}/><span>{t('category.deleteKeepsItems')}</span></div><div className="category-impact-list">{impact.categories.slice(0,8).map(category=><span key={category.id}>{category.pathLabel||category.name}</span>)}</div><div className="modal-actions"><button className="icon-btn" autoFocus onClick={onCancel}>{t('common.cancel')}</button><button className="icon-btn danger-action" disabled={deleting} onClick={async()=>{setDeleting(true);try{await onConfirm();}finally{setDeleting(false);}}}>{t('common.delete')}</button></div></div></div>;
}

export default function PublicContentManager(){
  const { t,errorMessage }=useI18n(); const generation=useRef(0);
  const [categories,setCategories]=useState([]),[items,setItems]=useState([]),[active,setActive]=useState('all'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [viewMode,setViewMode]=useState(()=>validView(localStorage.getItem('navpilot_view_mode_v1'))),[editingItem,setEditingItem]=useState(null),[showAi,setShowAi]=useState(false),[checking,setChecking]=useState(new Set()),[checkingAll,setCheckingAll]=useState(false),[deleteImpact,setDeleteImpact]=useState(null);
  const load=useCallback(async()=>{const current=++generation.current;setLoading(true);try{const [nextCategories,nextItems]=await Promise.all([api.listCategories('public'),api.listItems('public')]);if(current!==generation.current)return;setCategories(nextCategories);setItems(nextItems);setError('');}catch(e){if(current===generation.current)setError(errorMessage(e));}finally{if(current===generation.current)setLoading(false);}},[errorMessage]);
  useEffect(()=>{load();const timer=setInterval(load,30000);return()=>{generation.current+=1;clearInterval(timer);};},[load]);
  useEffect(()=>localStorage.setItem('navpilot_view_mode_v1',viewMode),[viewMode]);
  const counts=useMemo(()=>{const value=categoryCounts(categories,items);return{...value.aggregate,uncategorized:value.direct.uncategorized||0,all:items.length};},[categories,items]);
  const filtered=useMemo(()=>filterByCategory(items,categories,active).filter(item=>!query.trim()||`${item.name} ${item.url} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase())),[items,categories,active,query]);
  const categoryById=useMemo(()=>new Map(categories.map(category=>[category.id,category])),[categories]);
  async function createCategory(body){await api.createCategory({...body,scope:'public'});await load();}
  async function requestDelete(category){try{setDeleteImpact(await api.getCategoryImpact(category.id));}catch(e){setError(errorMessage(e));}}
  async function confirmDelete(){await api.deleteCategory(deleteImpact.category.id,{expectedVersion:deleteImpact.category.version,impactHash:deleteImpact.impactHash,confirmSubtree:true});setDeleteImpact(null);setActive('all');await load();}
  async function saveItem(form){if(editingItem?.id)await api.updateItem(editingItem.id,form);else await api.createItem({...form,scope:'public'});setEditingItem(null);await load();}
  async function deleteItem(item){if(!confirm(t('confirm.deleteItem',{name:item.name})))return;await api.deleteItem(item.id);setEditingItem(null);await load();}
  async function recheck(item){setChecking(current=>new Set(current).add(item.id));try{await api.checkItem(item.id);await load();}catch(e){setError(errorMessage(e));}finally{setChecking(current=>{const next=new Set(current);next.delete(item.id);return next;});}}
  async function checkAll(){setCheckingAll(true);setChecking(new Set(items.map(item=>item.id)));try{await api.checkAll('public');await load();}catch(e){setError(errorMessage(e));}finally{setCheckingAll(false);setChecking(new Set());}}
  const renderItems=list=><div className={viewMode==='compact'?'compact-list':viewMode==='overview'?'overview-resource-list':'grid'}>{list.map(item=><NavCard key={item.id} item={item} viewMode={viewMode} checking={checking.has(item.id)} canManage onClick={()=>{}} onEdit={()=>setEditingItem(item)} onDelete={()=>deleteItem(item)} onRecheck={()=>recheck(item)}/>)}</div>;
  return <section className="public-content-manager"><div className="public-content-heading"><div><h2>{t('admin.publicContent')}</h2><p>{t('admin.publicContentDesc')}</p></div><div className="public-content-actions"><button className="icon-btn" onClick={()=>setEditingItem({category_id:typeof active==='number'?active:null})}><Icon name="plus" size={15}/>{t('nav.add')}</button><button className="icon-btn" onClick={()=>setShowAi(true)}><Icon name="assistant" size={15}/>{t('nav.aiAdd')}</button><button className="icon-btn" disabled={checkingAll||checking.size>0} onClick={checkAll}><Icon name="refresh" size={15}/>{t(checkingAll?'category.checkingAll':'nav.checkAll')}</button></div></div><div className="public-content-toolbar"><div className="search-box"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('app.search')}/></div><span>{t('app.total',{count:items.length})}</span><ViewModeSwitcher value={viewMode} onChange={setViewMode}/></div>{error&&<div className="error-text">{error}</div>}<div className="public-content-layout"><CategoryNav categories={categories} counts={counts} active={active} onSelect={setActive} manageable onCreate={createCategory} onDelete={requestDelete}/><main className="public-content-main">{loading?<div className="empty-state">{t('app.loading')}</div>:!filtered.length?<div className="empty-state">{t(query?'app.noMatch':'app.publicEmpty')}</div>:active!=='all'?renderItems(filtered):<>{categories.filter(category=>category.parent_id==null).map(category=>{const list=filterByCategory(items,categories,category.id);if(!list.length)return null;return <section className="category-section" key={category.id}><h3 className="category-heading"><ContentIcon value={category.icon} size={18}/><span className="eyebrow">{category.name}</span><span className="sub">{t('app.itemsCount',{count:list.length})}</span></h3>{renderItems(list)}</section>;})}{items.some(item=>!item.category_id)&&<section className="category-section"><h3 className="category-heading"><ContentIcon value="📎" size={18}/><span className="eyebrow">{t('category.uncategorized')}</span><span className="sub">{t('app.itemsCount',{count:items.filter(item=>!item.category_id).length})}</span></h3>{renderItems(items.filter(item=>!item.category_id))}</section>}</>}</main></div>{editingItem!==null&&<ItemFormModal item={editingItem} categories={categories} scope="public" onClose={()=>setEditingItem(null)} onSubmit={saveItem} onDelete={()=>deleteItem(editingItem)}/>} {showAi&&<AiAddModal onClose={()=>setShowAi(false)} onCreated={async()=>{setShowAi(false);await load();}}/>}{deleteImpact&&<DeleteCategoryDialog impact={deleteImpact} onCancel={()=>setDeleteImpact(null)} onConfirm={confirmDelete}/>}</section>;
}
